// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Label         *string
	RecipientName string
	Phone         string
	Line1         string
	Line2         *string
	Landmark      *string
	City          string
	State         string
	Pincode       string
	IsDefault     bool
	DeletedAt     *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AdminAuditLog struct {
	ID          uuid.UUID
	AdminUserID uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Before      []byte
	After       []byte
	CreatedAt   time.Time
}

type CustomerProfile struct {
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PasswordSetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	UserAgent  *string
	CreatedAt  time.Time
}

type Supplier struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	BusinessName      string
	ContactName       string
	Phone             string
	Email             string
	Gstin             *string
	Pan               *string
	AddressLine1      *string
	AddressLine2      *string
	City              *string
	State             *string
	Pincode           *string
	BankAccountName   *string
	BankAccountNumber *string
	BankIfsc          *string
	Status            string
	ApprovedBy        *uuid.UUID
	ApprovedAt        *time.Time
	RejectionReason   *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	// Commission in basis points deducted from this supplier's payout. NULL means use the platform default (SUPPLIER_COMMISSION_BPS).
	CommissionBps *int32
}

type SupplierEventsOutbox struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	EventType     string
	SchemaVersion int16
	OccurredAt    time.Time
	ActorRole     string
	RequestID     *string
	Payload       []byte
	CreatedAt     time.Time
}

type User struct {
	ID            uuid.UUID
	Email         *string
	Phone         *string
	PasswordHash  *string
	Role          string
	Status        string
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
