// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminUpdateSupplier = `-- name: AdminUpdateSupplier :one
UPDATE suppliers
SET business_name       = $2,
    contact_name        = $3,
    phone               = $4,
    email               = $5,
    gstin               = $6,
    pan                 = $7,
    address_line1       = $8,
    address_line2       = $9,
    city                = $10,
    state               = $11,
    pincode             = $12,
    bank_account_name   = $13,
    bank_account_number = $14,
    bank_ifsc           = $15,
    -- NULL clears an override back to the platform default, which is why this
    -- is a plain assignment rather than a COALESCE that could never unset it.
    commission_bps      = $16
WHERE id = $1
RETURNING id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps
`

type AdminUpdateSupplierParams struct {
	ID                uuid.UUID
	BusinessName      string
	ContactName       string
	Phone             string
	Email             string
	Gstin             *string
	Pan               *string
	AddressLine1      *string
	AddressLine2      *string
	City              *string
	State             *string
	Pincode           *string
	BankAccountName   *string
	BankAccountNumber *string
	BankIfsc          *string
	CommissionBps     *int32
}

// Admin edit of a supplier's business, contact and bank details.
//
// Deliberately does NOT touch status: approval, rejection and suspension are
// their own audited transitions, and folding them into a general-purpose
// update would let a careless PATCH silently approve a pending applicant.
func (q *Queries) AdminUpdateSupplier(ctx context.Context, arg AdminUpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, adminUpdateSupplier,
		arg.ID,
		arg.BusinessName,
		arg.ContactName,
		arg.Phone,
		arg.Email,
		arg.Gstin,
		arg.Pan,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.BankAccountName,
		arg.BankAccountNumber,
		arg.BankIfsc,
		arg.CommissionBps,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const approveSupplier = `-- name: ApproveSupplier :one
UPDATE suppliers
SET status = 'approved', approved_by = $2, approved_at = now(), rejection_reason = NULL
WHERE id = $1
RETURNING id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps
`

type ApproveSupplierParams struct {
	ID         uuid.UUID
	ApprovedBy *uuid.UUID
}

func (q *Queries) ApproveSupplier(ctx context.Context, arg ApproveSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, approveSupplier, arg.ID, arg.ApprovedBy)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE addresses SET is_default = FALSE
WHERE user_id = $1 AND is_default AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const countLiveAddresses = `-- name: CountLiveAddresses :one
SELECT count(*) FROM addresses WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveAddresses(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingSupplierApplications = `-- name: CountPendingSupplierApplications :one
SELECT count(*) FROM suppliers WHERE status = 'pending'
`

func (q *Queries) CountPendingSupplierApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSupplierApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT count(*) FROM suppliers
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountSuppliers(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one

INSERT INTO addresses (
    user_id, label, recipient_name, phone,
    line1, line2, landmark, city, state, pincode, is_default
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at
`

type CreateAddressParams struct {
	UserID        uuid.UUID
	Label         *string
	RecipientName string
	Phone         string
	Line1         string
	Line2         *string
	Landmark      *string
	City          string
	State         string
	Pincode       string
	IsDefault     bool
}

// ===========================================================================
// addresses
// ===========================================================================
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.Landmark,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerProfile = `-- name: CreateCustomerProfile :one

INSERT INTO customer_profiles (user_id, name)
VALUES ($1, $2)
RETURNING user_id, name, created_at, updated_at
`

type CreateCustomerProfileParams struct {
	UserID uuid.UUID
	Name   string
}

// ===========================================================================
// customer_profiles
// ===========================================================================
func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error) {
	row := q.db.QueryRow(ctx, createCustomerProfile, arg.UserID, arg.Name)
	var i CustomerProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordSetToken = `-- name: CreatePasswordSetToken :one

INSERT INTO password_set_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordSetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// ===========================================================================
// password_set_tokens
// ===========================================================================
func (q *Queries) CreatePasswordSetToken(ctx context.Context, arg CreatePasswordSetTokenParams) (PasswordSetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordSetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordSetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UserAgent *string
}

// ===========================================================================
// refresh_tokens
// ===========================================================================
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one

INSERT INTO suppliers (
    user_id, business_name, contact_name, phone, email, gstin, pan,
    address_line1, address_line2, city, state, pincode,
    bank_account_name, bank_account_number, bank_ifsc,
    status, approved_by, approved_at, commission_bps
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps
`

type CreateSupplierParams struct {
	UserID            uuid.UUID
	BusinessName      string
	ContactName       string
	Phone             string
	Email             string
	Gstin             *string
	Pan               *string
	AddressLine1      *string
	AddressLine2      *string
	City              *string
	State             *string
	Pincode           *string
	BankAccountName   *string
	BankAccountNumber *string
	BankIfsc          *string
	Status            string
	ApprovedBy        *uuid.UUID
	ApprovedAt        *time.Time
	CommissionBps     *int32
}

// ===========================================================================
// suppliers
// ===========================================================================
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.UserID,
		arg.BusinessName,
		arg.ContactName,
		arg.Phone,
		arg.Email,
		arg.Gstin,
		arg.Pan,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.BankAccountName,
		arg.BankAccountNumber,
		arg.BankIfsc,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.CommissionBps,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (email, phone, password_hash, role, status, email_verified)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, phone, password_hash, role, status, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email         *string
	Phone         *string
	PasswordHash  *string
	Role          string
	Status        string
	EmailVerified bool
}

// Queries for vm-profile-api. Generated into Go by sqlc (CLAUDE.md §3), so
// every statement is parameterised by construction — rule 7.
//
// Ownership note: queries that read or mutate a resource belonging to a user
// take the owner's id as a parameter and filter on it IN SQL. Checking
// ownership in Go after an unfiltered fetch is one forgotten `if` away from
// an IDOR; this way the wrong row is never returned in the first place.
// ===========================================================================
// users
// ===========================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAddress = `-- name: GetAddress :one
SELECT id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at FROM addresses
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Ownership is part of the WHERE clause, not a later check.
func (q *Queries) GetAddress(ctx context.Context, arg GetAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT user_id, name, created_at, updated_at FROM customer_profiles WHERE user_id = $1
`

func (q *Queries) GetCustomerProfile(ctx context.Context, userID uuid.UUID) (CustomerProfile, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, userID)
	var i CustomerProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerWithProfile = `-- name: GetCustomerWithProfile :one
SELECT
    u.id, u.email, u.phone, u.role, u.status, u.email_verified, u.created_at,
    cp.name
FROM users u
JOIN customer_profiles cp ON cp.user_id = u.id
WHERE u.id = $1
`

type GetCustomerWithProfileRow struct {
	ID            uuid.UUID
	Email         *string
	Phone         *string
	Role          string
	Status        string
	EmailVerified bool
	CreatedAt     time.Time
	Name          string
}

// Joined view for GET /me, so the handler makes one round trip.
func (q *Queries) GetCustomerWithProfile(ctx context.Context, id uuid.UUID) (GetCustomerWithProfileRow, error) {
	row := q.db.QueryRow(ctx, getCustomerWithProfile, id)
	var i GetCustomerWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getPasswordSetTokenByHash = `-- name: GetPasswordSetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_set_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordSetTokenByHash(ctx context.Context, tokenHash string) (PasswordSetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordSetTokenByHash, tokenHash)
	var i PasswordSetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at FROM refresh_tokens WHERE token_hash = $1
`

// Looked up by hash only: the plaintext token is never stored, so this is the
// only way to find the row.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at FROM refresh_tokens WHERE id = $1
`

// The successor of a rotated token, used by the replay grace window.
func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const getSupplierByUserID = `-- name: GetSupplierByUserID :one
SELECT id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps FROM suppliers WHERE user_id = $1
`

func (q *Queries) GetSupplierByUserID(ctx context.Context, userID uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByUserID, userID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, role, status, email_verified, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, role, status, email_verified, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, password_hash, role, status, email_verified, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO admin_audit_log (admin_user_id, action, entity_type, entity_id, before, after)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, admin_user_id, action, entity_type, entity_id, before, after, created_at
`

type InsertAuditLogParams struct {
	AdminUserID uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Before      []byte
	After       []byte
}

// ===========================================================================
// admin_audit_log
// ===========================================================================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.AdminUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.CreatedAt,
	)
	return i, err
}

const insertSupplierEvent = `-- name: InsertSupplierEvent :one

INSERT INTO supplier_events_outbox (
    aggregate_id, event_type, schema_version, occurred_at, actor_role, request_id, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertSupplierEventParams struct {
	AggregateID   uuid.UUID
	EventType     string
	SchemaVersion int16
	OccurredAt    time.Time
	ActorRole     string
	RequestID     *string
	Payload       []byte
}

// ===========================================================================
// analytics supplier events — CLAUDE.md §5.4
// ===========================================================================
// Written in the caller's transaction, next to the change it describes.
func (q *Queries) InsertSupplierEvent(ctx context.Context, arg InsertSupplierEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSupplierEvent,
		arg.AggregateID,
		arg.EventType,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.ActorRole,
		arg.RequestID,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at FROM addresses
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, created_at DESC
`

// Default first, then newest, so the checkout form's first option is the
// one the customer expects.
func (q *Queries) ListAddresses(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.RecipientName,
			&i.Phone,
			&i.Line1,
			&i.Line2,
			&i.Landmark,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.IsDefault,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedSupplierIDs = `-- name: ListApprovedSupplierIDs :many
SELECT s.id
FROM suppliers s
JOIN users u ON u.id = s.user_id
WHERE s.status = 'approved' AND u.status = 'active'
ORDER BY s.id
`

// Approved supplier ids, for vm-catalog-api's storefront allow-list.
// CLAUDE.md §3 forbids cross-schema reads, so catalog asks over HTTP instead.
func (q *Queries) ListApprovedSupplierIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listApprovedSupplierIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogForEntity = `-- name: ListAuditLogForEntity :many
SELECT id, admin_user_id, action, entity_type, entity_id, before, after, created_at FROM admin_audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAuditLogForEntityParams struct {
	EntityType string
	EntityID   *uuid.UUID
	Limit      int32
}

func (q *Queries) ListAuditLogForEntity(ctx context.Context, arg ListAuditLogForEntityParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogForEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerContacts = `-- name: ListCustomerContacts :many
SELECT u.id, u.email, coalesce(p.name, '')::text AS name
FROM users u
LEFT JOIN customer_profiles p ON p.user_id = u.id
WHERE u.id = ANY($1::uuid[]) AND u.email IS NOT NULL
`

type ListCustomerContactsRow struct {
	ID    uuid.UUID
	Email *string
	Name  string
}

// Contact details for a set of customers, for transactional email.
//
// Service-to-service only. Returns the ADDRESS AND NAME and nothing else: the
// outbox dispatcher in vm-orders-api needs somewhere to send an order
// confirmation, and no more than that. Customers with no email — a phone-only
// signup — simply do not come back, which the caller reads as "cannot email
// this one" rather than as an error (CLAUDE.md §5.1 allows email to be NULL).
func (q *Queries) ListCustomerContacts(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCustomerContactsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerContacts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerContactsRow{}
	for rows.Next() {
		var i ListCustomerContactsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierBankDetails = `-- name: ListSupplierBankDetails :many
SELECT id, business_name, bank_account_name, bank_account_number, bank_ifsc
FROM suppliers
WHERE id = ANY($1::uuid[])
ORDER BY business_name
`

type ListSupplierBankDetailsRow struct {
	ID                uuid.UUID
	BusinessName      string
	BankAccountName   *string
	BankAccountNumber *string
	BankIfsc          *string
}

// Unmasked bank details for the admin settlement worksheet.
// The ONLY query that returns an account number in the clear; every caller
// must audit the access (CLAUDE.md §5.1).
func (q *Queries) ListSupplierBankDetails(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierBankDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSupplierBankDetails, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplierBankDetailsRow{}
	for rows.Next() {
		var i ListSupplierBankDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessName,
			&i.BankAccountName,
			&i.BankAccountNumber,
			&i.BankIfsc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierCommissions = `-- name: ListSupplierCommissions :many
SELECT id, commission_bps FROM suppliers
WHERE id = ANY($1::uuid[])
`

type ListSupplierCommissionsRow struct {
	ID            uuid.UUID
	CommissionBps *int32
}

// Commission rates for the payout calculation in vm-orders-api.
//
// Rates only — no contact, address or bank fields. The response shape is the
// access control: orders-api needs to know what to deduct and nothing else,
// so there is nothing here to leak even if the call is mis-scoped.
// NULL commission_bps means "use the platform default"; the caller decides
// what that is, because the default lives in orders-api's configuration.
func (q *Queries) ListSupplierCommissions(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierCommissionsRow, error) {
	rows, err := q.db.Query(ctx, listSupplierCommissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplierCommissionsRow{}
	for rows.Next() {
		var i ListSupplierCommissionsRow
		if err := rows.Scan(&i.ID, &i.CommissionBps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierIDsAfter = `-- name: ListSupplierIDsAfter :many
SELECT id, created_at FROM suppliers
WHERE (created_at, id) > ($1::timestamptz, $2::uuid)
ORDER BY created_at, id
LIMIT $3
`

type ListSupplierIDsAfterParams struct {
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

type ListSupplierIDsAfterRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// The backfill's cursor: every supplier, oldest first, a page at a time.
func (q *Queries) ListSupplierIDsAfter(ctx context.Context, arg ListSupplierIDsAfterParams) ([]ListSupplierIDsAfterRow, error) {
	rows, err := q.db.Query(ctx, listSupplierIDsAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplierIDsAfterRow{}
	for rows.Next() {
		var i ListSupplierIDsAfterRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierNames = `-- name: ListSupplierNames :many
SELECT id, business_name FROM suppliers
WHERE id = ANY($1::uuid[])
ORDER BY business_name
`

type ListSupplierNamesRow struct {
	ID           uuid.UUID
	BusinessName string
}

// Masked-safe directory for admin screens that only need names.
func (q *Queries) ListSupplierNames(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierNamesRow, error) {
	rows, err := q.db.Query(ctx, listSupplierNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupplierNamesRow{}
	for rows.Next() {
		var i ListSupplierNamesRow
		if err := rows.Scan(&i.ID, &i.BusinessName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps FROM suppliers
WHERE ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32
	Offset int32
	Status *string
}

// sqlc.narg means "optional": a NULL status returns every supplier.
func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessName,
			&i.ContactName,
			&i.Phone,
			&i.Email,
			&i.Gstin,
			&i.Pan,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.BankAccountName,
			&i.BankAccountNumber,
			&i.BankIfsc,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteNewestAddressToDefault = `-- name: PromoteNewestAddressToDefault :exec
UPDATE addresses AS a SET is_default = TRUE
WHERE a.id = (
    SELECT inner_a.id FROM addresses AS inner_a
    WHERE inner_a.user_id = $1 AND inner_a.deleted_at IS NULL
    ORDER BY inner_a.created_at DESC
    LIMIT 1
)
`

// Promotes the most recent remaining address after the default was deleted,
// so a customer is never left with addresses but no default.
// Aliased on both sides: without it, `user_id` is ambiguous between the outer
// UPDATE target and the subquery's own scan of the same table.
func (q *Queries) PromoteNewestAddressToDefault(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteNewestAddressToDefault, userID)
	return err
}

const pruneSupplierEvents = `-- name: PruneSupplierEvents :execrows
DELETE FROM supplier_events_outbox WHERE created_at < $1
`

// Retention. CDC has already read these from the WAL.
func (q *Queries) PruneSupplierEvents(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSupplierEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectSupplier = `-- name: RejectSupplier :one
UPDATE suppliers
SET status = 'rejected', rejection_reason = $2
WHERE id = $1
RETURNING id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps
`

type RejectSupplierParams struct {
	ID              uuid.UUID
	RejectionReason *string
}

func (q *Queries) RejectSupplier(ctx context.Context, arg RejectSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, rejectSupplier, arg.ID, arg.RejectionReason)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// The reuse-detection hammer: one replayed token invalidates every session
// for that user, because we can no longer tell which holder is legitimate.
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = now(), replaced_by = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at
`

type RevokeRefreshTokenParams struct {
	ID         uuid.UUID
	ReplacedBy *uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE addresses SET is_default = TRUE
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users SET password_hash = $2 WHERE id = $1
RETURNING id, email, phone, password_hash, role, status, email_verified, created_at, updated_at
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $2 WHERE id = $1
RETURNING id, email, phone, password_hash, role, status, email_verified, created_at, updated_at
`

type SetUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAddress = `-- name: SoftDeleteAddress :one
UPDATE addresses
SET deleted_at = now(), is_default = FALSE
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at
`

type SoftDeleteAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteAddress(ctx context.Context, arg SoftDeleteAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, softDeleteAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const suspendSupplier = `-- name: SuspendSupplier :one
UPDATE suppliers
SET status = 'suspended'
WHERE id = $1
RETURNING id, user_id, business_name, contact_name, phone, email, gstin, pan, address_line1, address_line2, city, state, pincode, bank_account_name, bank_account_number, bank_ifsc, status, approved_by, approved_at, rejection_reason, created_at, updated_at, commission_bps
`

func (q *Queries) SuspendSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, suspendSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Pan,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.BankIfsc,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBps,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses SET
    label          = $3,
    recipient_name = $4,
    phone          = $5,
    line1          = $6,
    line2          = $7,
    landmark       = $8,
    city           = $9,
    state          = $10,
    pincode        = $11
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, label, recipient_name, phone, line1, line2, landmark, city, state, pincode, is_default, deleted_at, created_at, updated_at
`

type UpdateAddressParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Label         *string
	RecipientName string
	Phone         string
	Line1         string
	Line2         *string
	Landmark      *string
	City          string
	State         string
	Pincode       string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.Landmark,
		arg.City,
		arg.State,
		arg.Pincode,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.IsDefault,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usePasswordSetToken = `-- name: UsePasswordSetToken :one
UPDATE password_set_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

func (q *Queries) UsePasswordSetToken(ctx context.Context, id uuid.UUID) (PasswordSetToken, error) {
	row := q.db.QueryRow(ctx, usePasswordSetToken, id)
	var i PasswordSetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
