// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Admin edit of a supplier's business, contact and bank details.
	//
	// Deliberately does NOT touch status: approval, rejection and suspension are
	// their own audited transitions, and folding them into a general-purpose
	// update would let a careless PATCH silently approve a pending applicant.
	AdminUpdateSupplier(ctx context.Context, arg AdminUpdateSupplierParams) (Supplier, error)
	ApproveSupplier(ctx context.Context, arg ApproveSupplierParams) (Supplier, error)
	ClearDefaultAddress(ctx context.Context, userID uuid.UUID) error
	CountLiveAddresses(ctx context.Context, userID uuid.UUID) (int64, error)
	CountPendingSupplierApplications(ctx context.Context) (int64, error)
	CountSuppliers(ctx context.Context, status *string) (int64, error)
	// ===========================================================================
	// addresses
	// ===========================================================================
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	// ===========================================================================
	// customer_profiles
	// ===========================================================================
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error)
	// ===========================================================================
	// password_set_tokens
	// ===========================================================================
	CreatePasswordSetToken(ctx context.Context, arg CreatePasswordSetTokenParams) (PasswordSetToken, error)
	// ===========================================================================
	// refresh_tokens
	// ===========================================================================
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// ===========================================================================
	// suppliers
	// ===========================================================================
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	// Queries for vm-profile-api. Generated into Go by sqlc (CLAUDE.md §3), so
	// every statement is parameterised by construction — rule 7.
	//
	// Ownership note: queries that read or mutate a resource belonging to a user
	// take the owner's id as a parameter and filter on it IN SQL. Checking
	// ownership in Go after an unfiltered fetch is one forgotten `if` away from
	// an IDOR; this way the wrong row is never returned in the first place.
	// ===========================================================================
	// users
	// ===========================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	// Ownership is part of the WHERE clause, not a later check.
	GetAddress(ctx context.Context, arg GetAddressParams) (Address, error)
	GetCustomerProfile(ctx context.Context, userID uuid.UUID) (CustomerProfile, error)
	// Joined view for GET /me, so the handler makes one round trip.
	GetCustomerWithProfile(ctx context.Context, id uuid.UUID) (GetCustomerWithProfileRow, error)
	GetPasswordSetTokenByHash(ctx context.Context, tokenHash string) (PasswordSetToken, error)
	// Looked up by hash only: the plaintext token is never stored, so this is the
	// only way to find the row.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	// The successor of a rotated token, used by the replay grace window.
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error)
	GetSupplierByUserID(ctx context.Context, userID uuid.UUID) (Supplier, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	// ===========================================================================
	// admin_audit_log
	// ===========================================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AdminAuditLog, error)
	// ===========================================================================
	// analytics supplier events — CLAUDE.md §5.4
	// ===========================================================================
	// Written in the caller's transaction, next to the change it describes.
	InsertSupplierEvent(ctx context.Context, arg InsertSupplierEventParams) (uuid.UUID, error)
	// Default first, then newest, so the checkout form's first option is the
	// one the customer expects.
	ListAddresses(ctx context.Context, userID uuid.UUID) ([]Address, error)
	// Approved supplier ids, for vm-catalog-api's storefront allow-list.
	// CLAUDE.md §3 forbids cross-schema reads, so catalog asks over HTTP instead.
	ListApprovedSupplierIDs(ctx context.Context) ([]uuid.UUID, error)
	ListAuditLogForEntity(ctx context.Context, arg ListAuditLogForEntityParams) ([]AdminAuditLog, error)
	// Contact details for a set of customers, for transactional email.
	//
	// Service-to-service only. Returns the ADDRESS AND NAME and nothing else: the
	// outbox dispatcher in vm-orders-api needs somewhere to send an order
	// confirmation, and no more than that. Customers with no email — a phone-only
	// signup — simply do not come back, which the caller reads as "cannot email
	// this one" rather than as an error (CLAUDE.md §5.1 allows email to be NULL).
	ListCustomerContacts(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCustomerContactsRow, error)
	// Unmasked bank details for the admin settlement worksheet.
	// The ONLY query that returns an account number in the clear; every caller
	// must audit the access (CLAUDE.md §5.1).
	ListSupplierBankDetails(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierBankDetailsRow, error)
	// Commission rates for the payout calculation in vm-orders-api.
	//
	// Rates only — no contact, address or bank fields. The response shape is the
	// access control: orders-api needs to know what to deduct and nothing else,
	// so there is nothing here to leak even if the call is mis-scoped.
	// NULL commission_bps means "use the platform default"; the caller decides
	// what that is, because the default lives in orders-api's configuration.
	ListSupplierCommissions(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierCommissionsRow, error)
	// The backfill's cursor: every supplier, oldest first, a page at a time.
	ListSupplierIDsAfter(ctx context.Context, arg ListSupplierIDsAfterParams) ([]ListSupplierIDsAfterRow, error)
	// Masked-safe directory for admin screens that only need names.
	ListSupplierNames(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSupplierNamesRow, error)
	// sqlc.narg means "optional": a NULL status returns every supplier.
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	// Promotes the most recent remaining address after the default was deleted,
	// so a customer is never left with addresses but no default.
	// Aliased on both sides: without it, `user_id` is ambiguous between the outer
	// UPDATE target and the subquery's own scan of the same table.
	PromoteNewestAddressToDefault(ctx context.Context, userID uuid.UUID) error
	// Retention. CDC has already read these from the WAL.
	PruneSupplierEvents(ctx context.Context, createdAt time.Time) (int64, error)
	RejectSupplier(ctx context.Context, arg RejectSupplierParams) (Supplier, error)
	// The reuse-detection hammer: one replayed token invalidates every session
	// for that user, because we can no longer tell which holder is legitimate.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) (int64, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (RefreshToken, error)
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	SoftDeleteAddress(ctx context.Context, arg SoftDeleteAddressParams) (Address, error)
	SuspendSupplier(ctx context.Context, id uuid.UUID) (Supplier, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UsePasswordSetToken(ctx context.Context, id uuid.UUID) (PasswordSetToken, error)
}

var _ Querier = (*Queries)(nil)
