// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type CsvImport struct {
	ID          uuid.UUID
	SupplierID  uuid.UUID
	Filename    string
	Status      string
	TotalRows   int32
	ValidRows   int32
	ErrorRows   int32
	Report      []byte
	CreatedAt   time.Time
	CommittedAt *time.Time
}

type DailyAvailability struct {
	ID            uuid.UUID
	SupplierID    uuid.UUID
	ProductID     uuid.UUID
	AvailableOn   time.Time
	TotalGrams    int32
	ReservedGrams int32
	SoldGrams     int32
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SizeCodeID    uuid.UUID
}

type Product struct {
	ID          uuid.UUID
	SupplierID  uuid.UUID
	Name        string
	Type        string
	Grade       *string
	Description *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// Admin markup in basis points of the supplier price (3000 = 30%). Never shown to the supplier.
	MarkupBps int32
}

type ProductEventsOutbox struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	EventType     string
	SchemaVersion int16
	OccurredAt    time.Time
	ActorRole     string
	RequestID     *string
	Payload       []byte
	CreatedAt     time.Time
}

// Images and videos for one SIZE CODE. Cover = first row of kind 'image' by sort_order.
type ProductMedium struct {
	ID          uuid.UUID
	ProductID   uuid.UUID
	Kind        string
	ObjectKey   string
	ContentType *string
	SortOrder   int32
	CreatedAt   time.Time
	// The grade these pictures are of, or NULL for media that belongs to the whole product and is shown after every grade's own.
	SizeCodeID *uuid.UUID
}

type ProductPackOption struct {
	ID          uuid.UUID
	SizeCodeID  uuid.UUID
	ProductID   uuid.UUID
	Label       string
	WeightGrams int32
	PricePaise  int64
	IsActive    bool
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// Optional customer-facing detail for this pack: "6-8 fruit", "ventilated carton". Free text, never parsed.
	Meta *string
}

// Grading level between a product and its packs. Carries the media and the daily stock.
type ProductSizeCode struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Code      string
	Meta      *string
	IsActive  bool
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
	// Roughly what percent of this product's harvest comes off as this grade. NULL means the grower has not said. Display only: no price, stock or fulfilment logic reads it.
	HarvestSharePct *int16
}

type StockHold struct {
	ID          uuid.UUID
	OrderRef    uuid.UUID
	ProductID   uuid.UUID
	AvailableOn time.Time
	Grams       int32
	Status      string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	SettledAt   *time.Time
	SizeCodeID  uuid.UUID
}
