// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveProductAsAdmin(ctx context.Context, id uuid.UUID) (Product, error)
	// Archive rather than delete: orders snapshot product details, but the
	// supplier's own history should still resolve (CLAUDE.md §5.3).
	ArchiveProductForSupplier(ctx context.Context, arg ArchiveProductForSupplierParams) (Product, error)
	// Today's declared stock for a specific set of products, unlocked.
	//
	// Feeds the cart's "you have asked for more than is left" check, which runs on
	// every cart read and must not take row locks or serialise against checkouts.
	// The numbers are therefore advisory: the authoritative check is the locked
	// one in LockAvailabilityForUpdate at reservation time. A product with no row
	// for the day simply does not come back, and the caller reads that as none
	// available.
	AvailabilityForSizeCodes(ctx context.Context, arg AvailabilityForSizeCodesParams) ([]AvailabilityForSizeCodesRow, error)
	// The sweeper's claim query. FOR UPDATE SKIP LOCKED lets several replicas
	// sweep concurrently without fighting over the same rows.
	ClaimExpiredHolds(ctx context.Context, limit int32) ([]StockHold, error)
	CloseAvailability(ctx context.Context, arg CloseAvailabilityParams) (DailyAvailability, error)
	// Committing moves grams from reserved to sold; the total is unchanged.
	CommitReservedGrams(ctx context.Context, arg CommitReservedGramsParams) (DailyAvailability, error)
	// DISTINCT because a product now joins one availability row per grade, and the
	// storefront counts cards.
	CountCatalog(ctx context.Context, arg CountCatalogParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	// How many of today's products can still be bought.
	//
	// Counted separately from CountCatalog because the storefront now lists sold-
	// out cards too: "12 items available today" must mean twelve buyable items,
	// not twelve cards of which four are greyed out.
	// A product counts once if ANY of its grades can still be bought.
	CountSellableCatalog(ctx context.Context, arg CountSellableCatalogParams) (int64, error)
	// ===========================================================================
	// csv_imports
	// ===========================================================================
	CreateCSVImport(ctx context.Context, arg CreateCSVImportParams) (CsvImport, error)
	// ===========================================================================
	// product_pack_options
	// ===========================================================================
	CreatePackOption(ctx context.Context, arg CreatePackOptionParams) (ProductPackOption, error)
	// Queries for vm-catalog-api. Generated into Go by sqlc (CLAUDE.md §3).
	//
	// Ownership rule: every supplier-facing query takes supplier_id and filters on
	// it IN SQL. A supplier can therefore never receive another supplier's row,
	// even if a handler forgets a check — the wrong row is never fetched.
	// ===========================================================================
	// products
	// ===========================================================================
	// markup_bps is passed in rather than left to the column default: the
	// platform's default rate is an env var (PRODUCT_MARKUP_DEFAULT_BPS), and a
	// second copy of it in the schema is a second thing to change.
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// ===========================================================================
	// product_units
	// ===========================================================================
	// ===========================================================================
	// product_size_codes
	// ===========================================================================
	CreateSizeCode(ctx context.Context, arg CreateSizeCodeParams) (ProductSizeCode, error)
	CreateStockHold(ctx context.Context, arg CreateStockHoldParams) (StockHold, error)
	// Releasing returns grams to the pool. GREATEST guards against a double
	// release ever driving the counter negative.
	DecrementReservedGrams(ctx context.Context, arg DecrementReservedGramsParams) (DailyAvailability, error)
	// The product-level bucket alone: the pictures that are of the FARM, not of a
	// grade. Replaced as a whole on save, exactly as each grade's gallery is.
	DeleteCommonMediaForProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	// The atomic half of "replace the size-code tree": delete all, then
	// re-insert, inside one transaction. Pack options and media cascade with it.
	DeleteSizeCodesForProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	GetAvailabilityForSizeCode(ctx context.Context, arg GetAvailabilityForSizeCodeParams) (DailyAvailability, error)
	// Supplier-scoped by id, so one supplier cannot close another's row.
	GetAvailabilityForSupplier(ctx context.Context, arg GetAvailabilityForSupplierParams) (DailyAvailability, error)
	// Supplier-scoped: one supplier must not be able to commit another's import.
	GetCSVImport(ctx context.Context, arg GetCSVImportParams) (CsvImport, error)
	// One product for the customer-facing detail page.
	//
	// LEFT JOIN, unlike ListCatalog's inner join, and no sold-out filter: someone
	// following a shared link to produce that has since sold out should reach the
	// page and be told so, not a 404 that reads as "this never existed". The
	// handler decides purchasability from the joined numbers; NULLs mean nothing
	// is declared for today.
	//
	// The supplier and status guards stay: a suspended grower's produce must not
	// be reachable by URL just because it is not reachable by browsing.
	// The product itself. Its grades and their stock come from
	// ListSizeCodeAvailability, so this stays one row however many grades there
	// are — no aggregate, no LEFT JOIN fan-out.
	GetCatalogProduct(ctx context.Context, arg GetCatalogProductParams) (Product, error)
	// Admin-only: no supplier filter.
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	// Supplier-scoped read. Ownership is the WHERE clause, not a later check.
	GetProductForSupplier(ctx context.Context, arg GetProductForSupplierParams) (Product, error)
	// Admin/internal read by id, no supplier filter. Used to name a grade in an
	// error message on the reserve path.
	GetSizeCode(ctx context.Context, id uuid.UUID) (ProductSizeCode, error)
	// Ownership check for the availability screen: resolves a size code only if it
	// belongs to a product of this supplier, and returns the product detail the
	// caller needs alongside — so a foreign id is a miss rather than a later
	// constraint violation.
	GetSizeCodeForSupplier(ctx context.Context, arg GetSizeCodeForSupplierParams) (GetSizeCodeForSupplierRow, error)
	IncrementReservedGrams(ctx context.Context, arg IncrementReservedGramsParams) (DailyAvailability, error)
	// ===========================================================================
	// analytics product events — CLAUDE.md §5.4
	// ===========================================================================
	// Written in the caller's transaction, next to the change it describes.
	InsertProductEvent(ctx context.Context, arg InsertProductEventParams) (uuid.UUID, error)
	InsertProductMedia(ctx context.Context, arg InsertProductMediaParams) (ProductMedium, error)
	// Source rows for copy-from-yesterday. Only products still active today are
	// worth copying, so the join filters them.
	ListAvailabilityForDate(ctx context.Context, arg ListAvailabilityForDateParams) ([]DailyAvailability, error)
	// ===========================================================================
	// daily_availability
	// ===========================================================================
	// The supplier's daily sheet: EVERY active size code, whether or not it has
	// been declared for this date. A LEFT JOIN rather than an inner one, because
	// "not declared today" is the state the screen most needs to show.
	//
	// One row per SIZE CODE, not per product: the grades are separate crates with
	// separate gram pools, so they are declared separately. Ordered by product
	// then the grower's own grade order, so the client can group without sorting.
	ListAvailabilitySheet(ctx context.Context, arg ListAvailabilitySheetParams) ([]ListAvailabilitySheetRow, error)
	ListCSVImports(ctx context.Context, arg ListCSVImportsParams) ([]CsvImport, error)
	// ===========================================================================
	// customer catalogue
	// ===========================================================================
	// Everything a customer sees on a given business day, sellable or not.
	//
	// The date is passed in by the CALLER, which always computes it server-side in
	// IST (CLAUDE.md rule 2) — a client-supplied date must never reach this query.
	// supplier_ids is the approved-supplier allow-list resolved from
	// vm-profile-api, so a suspended supplier's produce disappears from the
	// storefront without any catalog-side state.
	//
	// Sold-out and closed produce is deliberately NOT filtered out. A product
	// declared for today that has since run out stays on the storefront as a
	// disabled card, so a customer who came looking for it learns it was listed
	// and went, rather than concluding we never sell it. Purchasability is decided
	// by the handler from status and the joined grams; the join to
	// daily_availability still bounds the page to what was declared for TODAY, so
	// produce nobody listed this morning is absent as before.
	//
	// One row per PRODUCT even though stock is now per size code: the storefront
	// shows one CARD per product, and paging must count products, not grades.
	// The grams are therefore summed across the grades declared today, and
	// `any_sellable` is true if ANY grade can still be bought — a product whose M
	// has gone but whose XL has not is still on sale.
	//
	// The per-grade rows the card needs to actually price something come from
	// ListSizeCodeAvailability, called with this page's product ids.
	// Sellable first, sold out last, alphabetical within each group: the shop
	// still leads with what can be bought, and paging stays stable because the
	// sort key is a function of the row, not of the request.
	ListCatalog(ctx context.Context, arg ListCatalogParams) ([]ListCatalogRow, error)
	// Distinct grades listed today, for the storefront's filter chips.
	//
	// Sold-out rows count here too, or picking "Grade A" would empty a page that
	// was showing Grade A cards a moment earlier.
	ListCatalogGrades(ctx context.Context, arg ListCatalogGradesParams) ([]*string, error)
	ListHoldsForOrder(ctx context.Context, orderRef uuid.UUID) ([]StockHold, error)
	// ===========================================================================
	// stock holds — CLAUDE.md §6.3
	// ===========================================================================
	// Everything vm-orders-api needs to price and validate a cart, for one day.
	//
	// Deliberately its own query rather than reusing ListCatalog. orders-api used
	// to read the customer-facing /catalog endpoint, which was fine until prices
	// split in two: that endpoint returns the CUSTOMER price and must never
	// return the markup beside it, and orders-api needs both — the customer price
	// to charge, the markup to know which part of it is not the grower's. Reading
	// both from one row is also what stops the two drifting between calls.
	//
	// No paging: this is one day's produce from a handful of growers, and a cart
	// can reference any of it.
	ListInternalUnitsForDate(ctx context.Context, arg ListInternalUnitsForDateParams) ([]ListInternalUnitsForDateRow, error)
	// The galleries for a page of products, in one round trip. Ordered by product
	// then size code so a caller can walk the rows and group them without a
	// second sort.
	//
	// LEFT JOIN, because a row with a NULL size_code_id belongs to the whole
	// product rather than to one grade. Those sort last within their product, so
	// a caller appending them to each grade's gallery gets the grower's order for
	// free — a grade's own pictures, then the farm.
	ListMediaForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductMedium, error)
	ListMediaForSizeCode(ctx context.Context, sizeCodeID *uuid.UUID) ([]ProductMedium, error)
	ListPackOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductPackOption, error)
	// Every pack across a page of products, ordered so a caller can group by size
	// code without a second sort.
	ListPackOptionsForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductPackOption, error)
	// The backfill's cursor: every product, oldest first, a page at a time.
	ListProductIDsAfter(ctx context.Context, arg ListProductIDsAfterParams) ([]ListProductIDsAfterRow, error)
	// Filters are all optional (sqlc.narg): a NULL means "no filter". Written as
	// one query rather than assembled in Go, so there is no string concatenation
	// anywhere near the SQL (rule 7).
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	// Today's grades and their stock, for a page of products.
	//
	// The companion to ListCatalog: that query pages over products, this one fills
	// in the grades each card and detail page offers. Ordered by the grower's own
	// grade order so the client groups without sorting.
	ListSizeCodeAvailability(ctx context.Context, arg ListSizeCodeAvailabilityParams) ([]ListSizeCodeAvailabilityRow, error)
	ListSizeCodesForProduct(ctx context.Context, productID uuid.UUID) ([]ProductSizeCode, error)
	// Bulk fetch for the list view: one query for a whole page of products rather
	// than N+1 round trips.
	ListSizeCodesForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductSizeCode, error)
	// Locks one availability row for update.
	//
	// The lock is now per SIZE CODE, which is what a gram pool belongs to: two
	// customers buying different grades of the same produce no longer serialise
	// against each other, and two buying the same grade still do.
	//
	// Callers MUST take these in a deterministic order (by size_code_id) across
	// the whole request, or two concurrent checkouts touching the same two grades
	// can deadlock by grabbing them in opposite orders.
	LockAvailabilityForUpdate(ctx context.Context, arg LockAvailabilityForUpdateParams) (DailyAvailability, error)
	// Filtered on status so a double-submit commits exactly once.
	MarkCSVImportCommitted(ctx context.Context, arg MarkCSVImportCommittedParams) (CsvImport, error)
	// ===========================================================================
	// development seed (mocks/)
	// ===========================================================================
	// The seed's idempotency check, in the same terms as the unique index
	// products_supplier_name_grade_key: a live product of this name and grade.
	ProductExistsForSupplier(ctx context.Context, arg ProductExistsForSupplierParams) (bool, error)
	// ===========================================================================
	// product_media
	// ===========================================================================
	// The cover photograph for products referenced by an order.
	//
	// Takes the FIRST size code's first image: an order line snapshots the pack it
	// bought but not which grade's gallery to show, and the default grade is the
	// one the storefront opens on.
	//
	// No status filter: an order placed months ago must still show its produce,
	// and by then the product may well be archived. Order lines snapshot the name
	// and price for exactly this reason (CLAUDE.md §5.3); the image is the one
	// thing they cannot snapshot, because what is stored is an object key whose
	// URL is minted at read time.
	// A grade's own picture wins; the product-level gallery is the fallback, so a
	// grower who only uploaded photographs of the farm still gets a thumbnail.
	ProductImagesForIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductImagesForIDsRow, error)
	// Retention. CDC has already read these from the WAL.
	PruneProductEvents(ctx context.Context, createdAt time.Time) (int64, error)
	// The deliberate counterpart to closing. Scoped to the owning supplier, and to
	// rows that are actually closed, so a replay is a no-op rather than a silent
	// success.
	ReopenAvailability(ctx context.Context, arg ReopenAvailabilityParams) (DailyAvailability, error)
	// Sets the admin markup on a product. Admin only — a supplier must never be
	// able to reach this, and never sees the column it writes.
	//
	// updated_at is deliberately NOT touched: it is the supplier's own signal for
	// when their listing last changed, and moving it because we repriced would
	// show a grower an edit they did not make.
	SetProductMarkup(ctx context.Context, arg SetProductMarkupParams) (Product, error)
	// Filtered on status so a double release or commit is a no-op rather than
	// double-counting grams.
	SettleStockHold(ctx context.Context, arg SettleStockHoldParams) (StockHold, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Upsert: re-declaring a product for the same day updates it rather than
	// failing on the (product_id, available_on) unique constraint.
	// Reserved and sold are never touched here — they belong to the order flow.
	// Updating the declared quantity must NOT reopen a closed product.
	//
	// This previously forced status='open' on every conflict. Because the supplier
	// screen submits every row it has a number for, editing one product silently
	// reopened every other product the supplier had closed that day — stock they
	// had deliberately stopped selling went back on sale. Reopening is now its own
	// explicit action below. New rows still start open.
	UpsertAvailability(ctx context.Context, arg UpsertAvailabilityParams) (DailyAvailability, error)
}

var _ Querier = (*Queries)(nil)
