// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProductAsAdmin = `-- name: ArchiveProductAsAdmin :one
UPDATE products SET status = 'archived'
WHERE id = $1 AND status <> 'archived'
RETURNING id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps
`

func (q *Queries) ArchiveProductAsAdmin(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, archiveProductAsAdmin, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const archiveProductForSupplier = `-- name: ArchiveProductForSupplier :one
UPDATE products SET status = 'archived'
WHERE id = $1 AND supplier_id = $2 AND status <> 'archived'
RETURNING id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps
`

type ArchiveProductForSupplierParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// Archive rather than delete: orders snapshot product details, but the
// supplier's own history should still resolve (CLAUDE.md §5.3).
func (q *Queries) ArchiveProductForSupplier(ctx context.Context, arg ArchiveProductForSupplierParams) (Product, error) {
	row := q.db.QueryRow(ctx, archiveProductForSupplier, arg.ID, arg.SupplierID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const availabilityForSizeCodes = `-- name: AvailabilityForSizeCodes :many
SELECT
    a.size_code_id,
    a.product_id,
    p.name  AS product_name,
    sc.code AS size_code,
    a.total_grams,
    a.reserved_grams,
    a.sold_grams,
    a.status
FROM daily_availability a
JOIN product_size_codes sc ON sc.id = a.size_code_id
JOIN products p ON p.id = a.product_id
WHERE a.available_on = $1 AND a.size_code_id = ANY($2::uuid[])
`

type AvailabilityForSizeCodesParams struct {
	AvailableOn time.Time
	Column2     []uuid.UUID
}

type AvailabilityForSizeCodesRow struct {
	SizeCodeID    uuid.UUID
	ProductID     uuid.UUID
	ProductName   string
	SizeCode      string
	TotalGrams    int32
	ReservedGrams int32
	SoldGrams     int32
	Status        string
}

// Today's declared stock for a specific set of products, unlocked.
//
// Feeds the cart's "you have asked for more than is left" check, which runs on
// every cart read and must not take row locks or serialise against checkouts.
// The numbers are therefore advisory: the authoritative check is the locked
// one in LockAvailabilityForUpdate at reservation time. A product with no row
// for the day simply does not come back, and the caller reads that as none
// available.
func (q *Queries) AvailabilityForSizeCodes(ctx context.Context, arg AvailabilityForSizeCodesParams) ([]AvailabilityForSizeCodesRow, error) {
	rows, err := q.db.Query(ctx, availabilityForSizeCodes, arg.AvailableOn, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityForSizeCodesRow{}
	for rows.Next() {
		var i AvailabilityForSizeCodesRow
		if err := rows.Scan(
			&i.SizeCodeID,
			&i.ProductID,
			&i.ProductName,
			&i.SizeCode,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimExpiredHolds = `-- name: ClaimExpiredHolds :many
SELECT id, order_ref, product_id, available_on, grams, status, expires_at, created_at, settled_at, size_code_id FROM stock_holds
WHERE status = 'held' AND expires_at < now()
ORDER BY expires_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The sweeper's claim query. FOR UPDATE SKIP LOCKED lets several replicas
// sweep concurrently without fighting over the same rows.
func (q *Queries) ClaimExpiredHolds(ctx context.Context, limit int32) ([]StockHold, error) {
	rows, err := q.db.Query(ctx, claimExpiredHolds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockHold{}
	for rows.Next() {
		var i StockHold
		if err := rows.Scan(
			&i.ID,
			&i.OrderRef,
			&i.ProductID,
			&i.AvailableOn,
			&i.Grams,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SettledAt,
			&i.SizeCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeAvailability = `-- name: CloseAvailability :one
UPDATE daily_availability
SET status = 'closed'
WHERE id = $1 AND supplier_id = $2 AND status = 'open'
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type CloseAvailabilityParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

func (q *Queries) CloseAvailability(ctx context.Context, arg CloseAvailabilityParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, closeAvailability, arg.ID, arg.SupplierID)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const commitReservedGrams = `-- name: CommitReservedGrams :one
UPDATE daily_availability
SET reserved_grams = GREATEST(0, reserved_grams - $3),
    sold_grams     = sold_grams + $3
WHERE size_code_id = $1 AND available_on = $2
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type CommitReservedGramsParams struct {
	SizeCodeID    uuid.UUID
	AvailableOn   time.Time
	ReservedGrams int32
}

// Committing moves grams from reserved to sold; the total is unchanged.
func (q *Queries) CommitReservedGrams(ctx context.Context, arg CommitReservedGramsParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, commitReservedGrams, arg.SizeCodeID, arg.AvailableOn, arg.ReservedGrams)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const countCatalog = `-- name: CountCatalog :one
SELECT count(DISTINCT p.id)
FROM products p
JOIN daily_availability a ON a.product_id = p.id
JOIN product_size_codes sc ON sc.id = a.size_code_id AND sc.is_active
WHERE a.available_on = $1::date
  AND p.status = 'active'
  AND p.supplier_id = ANY($2::uuid[])
  AND ($3::text  IS NULL OR p.type  = $3::text)
  AND ($4::text IS NULL OR p.grade = $4::text)
  AND ($5::text IS NULL OR p.name ILIKE '%' || $5::text || '%')
`

type CountCatalogParams struct {
	AvailableOn time.Time
	SupplierIds []uuid.UUID
	Type        *string
	Grade       *string
	Search      *string
}

// DISTINCT because a product now joins one availability row per grade, and the
// storefront counts cards.
func (q *Queries) CountCatalog(ctx context.Context, arg CountCatalogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalog,
		arg.AvailableOn,
		arg.SupplierIds,
		arg.Type,
		arg.Grade,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE ($1::uuid IS NULL OR supplier_id = $1::uuid)
  AND ($2::text   IS NULL OR type   = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR name ILIKE '%' || $4::text || '%')
`

type CountProductsParams struct {
	SupplierID *uuid.UUID
	Type       *string
	Status     *string
	Search     *string
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.SupplierID,
		arg.Type,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSellableCatalog = `-- name: CountSellableCatalog :one
SELECT count(DISTINCT p.id)
FROM products p
JOIN daily_availability a ON a.product_id = p.id
JOIN product_size_codes sc ON sc.id = a.size_code_id AND sc.is_active
WHERE a.available_on = $1::date
  AND a.status = 'open'
  AND a.total_grams > a.reserved_grams + a.sold_grams
  AND p.status = 'active'
  AND p.supplier_id = ANY($2::uuid[])
  AND ($3::text  IS NULL OR p.type  = $3::text)
  AND ($4::text IS NULL OR p.grade = $4::text)
  AND ($5::text IS NULL OR p.name ILIKE '%' || $5::text || '%')
`

type CountSellableCatalogParams struct {
	AvailableOn time.Time
	SupplierIds []uuid.UUID
	Type        *string
	Grade       *string
	Search      *string
}

// How many of today's products can still be bought.
//
// Counted separately from CountCatalog because the storefront now lists sold-
// out cards too: "12 items available today" must mean twelve buyable items,
// not twelve cards of which four are greyed out.
// A product counts once if ANY of its grades can still be bought.
func (q *Queries) CountSellableCatalog(ctx context.Context, arg CountSellableCatalogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSellableCatalog,
		arg.AvailableOn,
		arg.SupplierIds,
		arg.Type,
		arg.Grade,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCSVImport = `-- name: CreateCSVImport :one

INSERT INTO csv_imports (
    supplier_id, filename, status, total_rows, valid_rows, error_rows, report
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, supplier_id, filename, status, total_rows, valid_rows, error_rows, report, created_at, committed_at
`

type CreateCSVImportParams struct {
	SupplierID uuid.UUID
	Filename   string
	Status     string
	TotalRows  int32
	ValidRows  int32
	ErrorRows  int32
	Report     []byte
}

// ===========================================================================
// csv_imports
// ===========================================================================
func (q *Queries) CreateCSVImport(ctx context.Context, arg CreateCSVImportParams) (CsvImport, error) {
	row := q.db.QueryRow(ctx, createCSVImport,
		arg.SupplierID,
		arg.Filename,
		arg.Status,
		arg.TotalRows,
		arg.ValidRows,
		arg.ErrorRows,
		arg.Report,
	)
	var i CsvImport
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Filename,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.ErrorRows,
		&i.Report,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const createPackOption = `-- name: CreatePackOption :one

INSERT INTO product_pack_options (
    size_code_id, product_id, label, meta, weight_grams, price_paise, is_active, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, size_code_id, product_id, label, weight_grams, price_paise, is_active, sort_order, created_at, updated_at, meta
`

type CreatePackOptionParams struct {
	SizeCodeID  uuid.UUID
	ProductID   uuid.UUID
	Label       string
	Meta        *string
	WeightGrams int32
	PricePaise  int64
	IsActive    bool
	SortOrder   int32
}

// ===========================================================================
// product_pack_options
// ===========================================================================
func (q *Queries) CreatePackOption(ctx context.Context, arg CreatePackOptionParams) (ProductPackOption, error) {
	row := q.db.QueryRow(ctx, createPackOption,
		arg.SizeCodeID,
		arg.ProductID,
		arg.Label,
		arg.Meta,
		arg.WeightGrams,
		arg.PricePaise,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ProductPackOption
	err := row.Scan(
		&i.ID,
		&i.SizeCodeID,
		&i.ProductID,
		&i.Label,
		&i.WeightGrams,
		&i.PricePaise,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Meta,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one


INSERT INTO products (
    supplier_id, name, type, grade, description, status, markup_bps
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps
`

type CreateProductParams struct {
	SupplierID  uuid.UUID
	Name        string
	Type        string
	Grade       *string
	Description *string
	Status      string
	MarkupBps   int32
}

// Queries for vm-catalog-api. Generated into Go by sqlc (CLAUDE.md §3).
//
// Ownership rule: every supplier-facing query takes supplier_id and filters on
// it IN SQL. A supplier can therefore never receive another supplier's row,
// even if a handler forgets a check — the wrong row is never fetched.
// ===========================================================================
// products
// ===========================================================================
// markup_bps is passed in rather than left to the column default: the
// platform's default rate is an env var (PRODUCT_MARKUP_DEFAULT_BPS), and a
// second copy of it in the schema is a second thing to change.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SupplierID,
		arg.Name,
		arg.Type,
		arg.Grade,
		arg.Description,
		arg.Status,
		arg.MarkupBps,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const createSizeCode = `-- name: CreateSizeCode :one


INSERT INTO product_size_codes (
    product_id, code, meta, is_active, sort_order, harvest_share_pct
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, code, meta, is_active, sort_order, created_at, updated_at, harvest_share_pct
`

type CreateSizeCodeParams struct {
	ProductID       uuid.UUID
	Code            string
	Meta            *string
	IsActive        bool
	SortOrder       int32
	HarvestSharePct *int16
}

// ===========================================================================
// product_units
// ===========================================================================
// ===========================================================================
// product_size_codes
// ===========================================================================
func (q *Queries) CreateSizeCode(ctx context.Context, arg CreateSizeCodeParams) (ProductSizeCode, error) {
	row := q.db.QueryRow(ctx, createSizeCode,
		arg.ProductID,
		arg.Code,
		arg.Meta,
		arg.IsActive,
		arg.SortOrder,
		arg.HarvestSharePct,
	)
	var i ProductSizeCode
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Meta,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HarvestSharePct,
	)
	return i, err
}

const createStockHold = `-- name: CreateStockHold :one
INSERT INTO stock_holds (
    order_ref, product_id, size_code_id, available_on, grams, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_ref, product_id, available_on, grams, status, expires_at, created_at, settled_at, size_code_id
`

type CreateStockHoldParams struct {
	OrderRef    uuid.UUID
	ProductID   uuid.UUID
	SizeCodeID  uuid.UUID
	AvailableOn time.Time
	Grams       int32
	ExpiresAt   time.Time
}

func (q *Queries) CreateStockHold(ctx context.Context, arg CreateStockHoldParams) (StockHold, error) {
	row := q.db.QueryRow(ctx, createStockHold,
		arg.OrderRef,
		arg.ProductID,
		arg.SizeCodeID,
		arg.AvailableOn,
		arg.Grams,
		arg.ExpiresAt,
	)
	var i StockHold
	err := row.Scan(
		&i.ID,
		&i.OrderRef,
		&i.ProductID,
		&i.AvailableOn,
		&i.Grams,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SettledAt,
		&i.SizeCodeID,
	)
	return i, err
}

const decrementReservedGrams = `-- name: DecrementReservedGrams :one
UPDATE daily_availability
SET reserved_grams = GREATEST(0, reserved_grams - $3)
WHERE size_code_id = $1 AND available_on = $2
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type DecrementReservedGramsParams struct {
	SizeCodeID    uuid.UUID
	AvailableOn   time.Time
	ReservedGrams int32
}

// Releasing returns grams to the pool. GREATEST guards against a double
// release ever driving the counter negative.
func (q *Queries) DecrementReservedGrams(ctx context.Context, arg DecrementReservedGramsParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, decrementReservedGrams, arg.SizeCodeID, arg.AvailableOn, arg.ReservedGrams)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const deleteCommonMediaForProduct = `-- name: DeleteCommonMediaForProduct :execrows
DELETE FROM product_media WHERE product_id = $1 AND size_code_id IS NULL
`

// The product-level bucket alone: the pictures that are of the FARM, not of a
// grade. Replaced as a whole on save, exactly as each grade's gallery is.
func (q *Queries) DeleteCommonMediaForProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommonMediaForProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSizeCodesForProduct = `-- name: DeleteSizeCodesForProduct :execrows
DELETE FROM product_size_codes WHERE product_id = $1
`

// The atomic half of "replace the size-code tree": delete all, then
// re-insert, inside one transaction. Pack options and media cascade with it.
func (q *Queries) DeleteSizeCodesForProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSizeCodesForProduct, productID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvailabilityForSizeCode = `-- name: GetAvailabilityForSizeCode :one
SELECT id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id FROM daily_availability
WHERE size_code_id = $1 AND available_on = $2
`

type GetAvailabilityForSizeCodeParams struct {
	SizeCodeID  uuid.UUID
	AvailableOn time.Time
}

func (q *Queries) GetAvailabilityForSizeCode(ctx context.Context, arg GetAvailabilityForSizeCodeParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, getAvailabilityForSizeCode, arg.SizeCodeID, arg.AvailableOn)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const getAvailabilityForSupplier = `-- name: GetAvailabilityForSupplier :one
SELECT id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id FROM daily_availability WHERE id = $1 AND supplier_id = $2
`

type GetAvailabilityForSupplierParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// Supplier-scoped by id, so one supplier cannot close another's row.
func (q *Queries) GetAvailabilityForSupplier(ctx context.Context, arg GetAvailabilityForSupplierParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, getAvailabilityForSupplier, arg.ID, arg.SupplierID)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const getCSVImport = `-- name: GetCSVImport :one
SELECT id, supplier_id, filename, status, total_rows, valid_rows, error_rows, report, created_at, committed_at FROM csv_imports WHERE id = $1 AND supplier_id = $2
`

type GetCSVImportParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// Supplier-scoped: one supplier must not be able to commit another's import.
func (q *Queries) GetCSVImport(ctx context.Context, arg GetCSVImportParams) (CsvImport, error) {
	row := q.db.QueryRow(ctx, getCSVImport, arg.ID, arg.SupplierID)
	var i CsvImport
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Filename,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.ErrorRows,
		&i.Report,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getCatalogProduct = `-- name: GetCatalogProduct :one
SELECT p.id, p.supplier_id, p.name, p.type, p.grade, p.description, p.status, p.created_at, p.updated_at, p.markup_bps
FROM products p
WHERE p.id = $1
  AND p.status = 'active'
  AND p.supplier_id = ANY($2::uuid[])
`

type GetCatalogProductParams struct {
	ID          uuid.UUID
	SupplierIds []uuid.UUID
}

// One product for the customer-facing detail page.
//
// LEFT JOIN, unlike ListCatalog's inner join, and no sold-out filter: someone
// following a shared link to produce that has since sold out should reach the
// page and be told so, not a 404 that reads as "this never existed". The
// handler decides purchasability from the joined numbers; NULLs mean nothing
// is declared for today.
//
// The supplier and status guards stay: a suspended grower's produce must not
// be reachable by URL just because it is not reachable by browsing.
// The product itself. Its grades and their stock come from
// ListSizeCodeAvailability, so this stays one row however many grades there
// are — no aggregate, no LEFT JOIN fan-out.
func (q *Queries) GetCatalogProduct(ctx context.Context, arg GetCatalogProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getCatalogProduct, arg.ID, arg.SupplierIds)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps FROM products WHERE id = $1
`

// Admin-only: no supplier filter.
func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const getProductForSupplier = `-- name: GetProductForSupplier :one
SELECT id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps FROM products WHERE id = $1 AND supplier_id = $2
`

type GetProductForSupplierParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// Supplier-scoped read. Ownership is the WHERE clause, not a later check.
func (q *Queries) GetProductForSupplier(ctx context.Context, arg GetProductForSupplierParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductForSupplier, arg.ID, arg.SupplierID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const getSizeCode = `-- name: GetSizeCode :one
SELECT id, product_id, code, meta, is_active, sort_order, created_at, updated_at, harvest_share_pct FROM product_size_codes WHERE id = $1
`

// Admin/internal read by id, no supplier filter. Used to name a grade in an
// error message on the reserve path.
func (q *Queries) GetSizeCode(ctx context.Context, id uuid.UUID) (ProductSizeCode, error) {
	row := q.db.QueryRow(ctx, getSizeCode, id)
	var i ProductSizeCode
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Meta,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HarvestSharePct,
	)
	return i, err
}

const getSizeCodeForSupplier = `-- name: GetSizeCodeForSupplier :one
SELECT
    sc.id, sc.product_id, sc.code, sc.meta, sc.is_active, sc.sort_order, sc.created_at, sc.updated_at, sc.harvest_share_pct,
    p.name  AS product_name,
    p.type  AS product_type,
    p.grade AS product_grade
FROM product_size_codes sc
JOIN products p ON p.id = sc.product_id
WHERE sc.id = $1 AND p.supplier_id = $2
`

type GetSizeCodeForSupplierParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

type GetSizeCodeForSupplierRow struct {
	ID              uuid.UUID
	ProductID       uuid.UUID
	Code            string
	Meta            *string
	IsActive        bool
	SortOrder       int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	HarvestSharePct *int16
	ProductName     string
	ProductType     string
	ProductGrade    *string
}

// Ownership check for the availability screen: resolves a size code only if it
// belongs to a product of this supplier, and returns the product detail the
// caller needs alongside — so a foreign id is a miss rather than a later
// constraint violation.
func (q *Queries) GetSizeCodeForSupplier(ctx context.Context, arg GetSizeCodeForSupplierParams) (GetSizeCodeForSupplierRow, error) {
	row := q.db.QueryRow(ctx, getSizeCodeForSupplier, arg.ID, arg.SupplierID)
	var i GetSizeCodeForSupplierRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Code,
		&i.Meta,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HarvestSharePct,
		&i.ProductName,
		&i.ProductType,
		&i.ProductGrade,
	)
	return i, err
}

const incrementReservedGrams = `-- name: IncrementReservedGrams :one
UPDATE daily_availability
SET reserved_grams = reserved_grams + $3
WHERE size_code_id = $1 AND available_on = $2
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type IncrementReservedGramsParams struct {
	SizeCodeID    uuid.UUID
	AvailableOn   time.Time
	ReservedGrams int32
}

func (q *Queries) IncrementReservedGrams(ctx context.Context, arg IncrementReservedGramsParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, incrementReservedGrams, arg.SizeCodeID, arg.AvailableOn, arg.ReservedGrams)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const insertProductEvent = `-- name: InsertProductEvent :one

INSERT INTO product_events_outbox (
    aggregate_id, event_type, schema_version, occurred_at, actor_role, request_id, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertProductEventParams struct {
	AggregateID   uuid.UUID
	EventType     string
	SchemaVersion int16
	OccurredAt    time.Time
	ActorRole     string
	RequestID     *string
	Payload       []byte
}

// ===========================================================================
// analytics product events — CLAUDE.md §5.4
// ===========================================================================
// Written in the caller's transaction, next to the change it describes.
func (q *Queries) InsertProductEvent(ctx context.Context, arg InsertProductEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProductEvent,
		arg.AggregateID,
		arg.EventType,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.ActorRole,
		arg.RequestID,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertProductMedia = `-- name: InsertProductMedia :one
INSERT INTO product_media (size_code_id, product_id, kind, object_key, content_type, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, kind, object_key, content_type, sort_order, created_at, size_code_id
`

type InsertProductMediaParams struct {
	SizeCodeID  *uuid.UUID
	ProductID   uuid.UUID
	Kind        string
	ObjectKey   string
	ContentType *string
	SortOrder   int32
}

func (q *Queries) InsertProductMedia(ctx context.Context, arg InsertProductMediaParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, insertProductMedia,
		arg.SizeCodeID,
		arg.ProductID,
		arg.Kind,
		arg.ObjectKey,
		arg.ContentType,
		arg.SortOrder,
	)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.ObjectKey,
		&i.ContentType,
		&i.SortOrder,
		&i.CreatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const listAvailabilityForDate = `-- name: ListAvailabilityForDate :many
SELECT a.id, a.supplier_id, a.product_id, a.available_on, a.total_grams, a.reserved_grams, a.sold_grams, a.status, a.created_at, a.updated_at, a.size_code_id
FROM daily_availability a
JOIN products p ON p.id = a.product_id AND p.status = 'active'
JOIN product_size_codes sc ON sc.id = a.size_code_id AND sc.is_active
WHERE a.supplier_id = $1 AND a.available_on = $2
ORDER BY p.name, sc.sort_order, sc.created_at
`

type ListAvailabilityForDateParams struct {
	SupplierID  uuid.UUID
	AvailableOn time.Time
}

// Source rows for copy-from-yesterday. Only products still active today are
// worth copying, so the join filters them.
func (q *Queries) ListAvailabilityForDate(ctx context.Context, arg ListAvailabilityForDateParams) ([]DailyAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityForDate, arg.SupplierID, arg.AvailableOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyAvailability{}
	for rows.Next() {
		var i DailyAvailability
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.ProductID,
			&i.AvailableOn,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SizeCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilitySheet = `-- name: ListAvailabilitySheet :many

SELECT
    p.id           AS product_id,
    p.name         AS product_name,
    p.type         AS product_type,
    p.grade        AS product_grade,
    sc.id          AS size_code_id,
    sc.code        AS size_code,
    sc.meta        AS size_meta,
    sc.sort_order  AS size_sort_order,
    -- The cover: first image of THIS grade's gallery, or of the product-level
    -- one when the grade has no picture of its own. COALESCE'd to '' because
    -- sqlc infers a scalar subquery as NOT NULL, and a grade with no
    -- photograph would otherwise fail to scan. Empty string is "no cover".
    coalesce((SELECT m.object_key
                FROM product_media m
               WHERE m.kind = 'image'
                 AND (m.size_code_id = sc.id
                      OR (m.size_code_id IS NULL AND m.product_id = p.id))
               ORDER BY (m.size_code_id IS NULL), m.sort_order, m.created_at
               LIMIT 1), '')::text AS product_image_key,
    a.id           AS availability_id,
    a.total_grams,
    a.reserved_grams,
    a.sold_grams,
    a.status       AS availability_status
FROM products p
JOIN product_size_codes sc ON sc.product_id = p.id AND sc.is_active
LEFT JOIN daily_availability a
       ON a.size_code_id = sc.id AND a.available_on = $2
WHERE p.supplier_id = $1
  AND p.status = 'active'
ORDER BY p.name, sc.sort_order, sc.created_at
`

type ListAvailabilitySheetParams struct {
	SupplierID  uuid.UUID
	AvailableOn time.Time
}

type ListAvailabilitySheetRow struct {
	ProductID          uuid.UUID
	ProductName        string
	ProductType        string
	ProductGrade       *string
	SizeCodeID         uuid.UUID
	SizeCode           string
	SizeMeta           *string
	SizeSortOrder      int32
	ProductImageKey    string
	AvailabilityID     *uuid.UUID
	TotalGrams         *int32
	ReservedGrams      *int32
	SoldGrams          *int32
	AvailabilityStatus *string
}

// ===========================================================================
// daily_availability
// ===========================================================================
// The supplier's daily sheet: EVERY active size code, whether or not it has
// been declared for this date. A LEFT JOIN rather than an inner one, because
// "not declared today" is the state the screen most needs to show.
//
// One row per SIZE CODE, not per product: the grades are separate crates with
// separate gram pools, so they are declared separately. Ordered by product
// then the grower's own grade order, so the client can group without sorting.
func (q *Queries) ListAvailabilitySheet(ctx context.Context, arg ListAvailabilitySheetParams) ([]ListAvailabilitySheetRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilitySheet, arg.SupplierID, arg.AvailableOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilitySheetRow{}
	for rows.Next() {
		var i ListAvailabilitySheetRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ProductType,
			&i.ProductGrade,
			&i.SizeCodeID,
			&i.SizeCode,
			&i.SizeMeta,
			&i.SizeSortOrder,
			&i.ProductImageKey,
			&i.AvailabilityID,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.AvailabilityStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCSVImports = `-- name: ListCSVImports :many
SELECT id, supplier_id, filename, status, total_rows, valid_rows, error_rows, report, created_at, committed_at FROM csv_imports
WHERE supplier_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCSVImportsParams struct {
	SupplierID uuid.UUID
	Limit      int32
}

func (q *Queries) ListCSVImports(ctx context.Context, arg ListCSVImportsParams) ([]CsvImport, error) {
	rows, err := q.db.Query(ctx, listCSVImports, arg.SupplierID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsvImport{}
	for rows.Next() {
		var i CsvImport
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Filename,
			&i.Status,
			&i.TotalRows,
			&i.ValidRows,
			&i.ErrorRows,
			&i.Report,
			&i.CreatedAt,
			&i.CommittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalog = `-- name: ListCatalog :many

SELECT
    p.id, p.supplier_id, p.name, p.type, p.grade, p.description, p.status, p.created_at, p.updated_at, p.markup_bps,
    sum(a.total_grams)::integer    AS total_grams,
    sum(a.reserved_grams)::integer AS reserved_grams,
    sum(a.sold_grams)::integer     AS sold_grams,
    bool_or(a.status = 'open'
            AND a.total_grams > a.reserved_grams + a.sold_grams)::boolean AS any_sellable
FROM products p
JOIN daily_availability a ON a.product_id = p.id
JOIN product_size_codes sc ON sc.id = a.size_code_id AND sc.is_active
WHERE a.available_on = $3::date
  AND p.status = 'active'
  AND p.supplier_id = ANY($4::uuid[])
  AND ($5::text  IS NULL OR p.type  = $5::text)
  AND ($6::text IS NULL OR p.grade = $6::text)
  AND ($7::text IS NULL OR p.name ILIKE '%' || $7::text || '%')
GROUP BY p.id
ORDER BY bool_or(a.status = 'open'
                 AND a.total_grams > a.reserved_grams + a.sold_grams) DESC,
         p.name
LIMIT $1 OFFSET $2
`

type ListCatalogParams struct {
	Limit       int32
	Offset      int32
	AvailableOn time.Time
	SupplierIds []uuid.UUID
	Type        *string
	Grade       *string
	Search      *string
}

type ListCatalogRow struct {
	ID            uuid.UUID
	SupplierID    uuid.UUID
	Name          string
	Type          string
	Grade         *string
	Description   *string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MarkupBps     int32
	TotalGrams    int32
	ReservedGrams int32
	SoldGrams     int32
	AnySellable   bool
}

// ===========================================================================
// customer catalogue
// ===========================================================================
// Everything a customer sees on a given business day, sellable or not.
//
// The date is passed in by the CALLER, which always computes it server-side in
// IST (CLAUDE.md rule 2) — a client-supplied date must never reach this query.
// supplier_ids is the approved-supplier allow-list resolved from
// vm-profile-api, so a suspended supplier's produce disappears from the
// storefront without any catalog-side state.
//
// Sold-out and closed produce is deliberately NOT filtered out. A product
// declared for today that has since run out stays on the storefront as a
// disabled card, so a customer who came looking for it learns it was listed
// and went, rather than concluding we never sell it. Purchasability is decided
// by the handler from status and the joined grams; the join to
// daily_availability still bounds the page to what was declared for TODAY, so
// produce nobody listed this morning is absent as before.
//
// One row per PRODUCT even though stock is now per size code: the storefront
// shows one CARD per product, and paging must count products, not grades.
// The grams are therefore summed across the grades declared today, and
// `any_sellable` is true if ANY grade can still be bought — a product whose M
// has gone but whose XL has not is still on sale.
//
// The per-grade rows the card needs to actually price something come from
// ListSizeCodeAvailability, called with this page's product ids.
// Sellable first, sold out last, alphabetical within each group: the shop
// still leads with what can be bought, and paging stays stable because the
// sort key is a function of the row, not of the request.
func (q *Queries) ListCatalog(ctx context.Context, arg ListCatalogParams) ([]ListCatalogRow, error) {
	rows, err := q.db.Query(ctx, listCatalog,
		arg.Limit,
		arg.Offset,
		arg.AvailableOn,
		arg.SupplierIds,
		arg.Type,
		arg.Grade,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogRow{}
	for rows.Next() {
		var i ListCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Name,
			&i.Type,
			&i.Grade,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MarkupBps,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.AnySellable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogGrades = `-- name: ListCatalogGrades :many
SELECT DISTINCT p.grade
FROM products p
JOIN daily_availability a ON a.product_id = p.id
JOIN product_size_codes sc ON sc.id = a.size_code_id AND sc.is_active
WHERE a.available_on = $1::date
  AND p.status = 'active'
  AND p.grade IS NOT NULL
  AND p.supplier_id = ANY($2::uuid[])
ORDER BY p.grade
`

type ListCatalogGradesParams struct {
	AvailableOn time.Time
	SupplierIds []uuid.UUID
}

// Distinct grades listed today, for the storefront's filter chips.
//
// Sold-out rows count here too, or picking "Grade A" would empty a page that
// was showing Grade A cards a moment earlier.
func (q *Queries) ListCatalogGrades(ctx context.Context, arg ListCatalogGradesParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, listCatalogGrades, arg.AvailableOn, arg.SupplierIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var grade *string
		if err := rows.Scan(&grade); err != nil {
			return nil, err
		}
		items = append(items, grade)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldsForOrder = `-- name: ListHoldsForOrder :many
SELECT id, order_ref, product_id, available_on, grams, status, expires_at, created_at, settled_at, size_code_id FROM stock_holds WHERE order_ref = $1 ORDER BY created_at
`

func (q *Queries) ListHoldsForOrder(ctx context.Context, orderRef uuid.UUID) ([]StockHold, error) {
	rows, err := q.db.Query(ctx, listHoldsForOrder, orderRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockHold{}
	for rows.Next() {
		var i StockHold
		if err := rows.Scan(
			&i.ID,
			&i.OrderRef,
			&i.ProductID,
			&i.AvailableOn,
			&i.Grams,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SettledAt,
			&i.SizeCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalUnitsForDate = `-- name: ListInternalUnitsForDate :many

SELECT
    u.id            AS unit_id,
    u.label,
    u.weight_grams,
    u.price_paise,
    p.id            AS product_id,
    p.supplier_id,
    p.name          AS product_name,
    -- Type and grade travel to vm-orders-api so they can be SNAPSHOTTED onto
    -- the order line (CLAUDE.md §5.3). Without them an order cannot say what
    -- kind of produce it was for, and no report downstream can either — the
    -- orders schema has no way to look either one up later.
    p.type          AS product_type,
    p.grade,
    p.markup_bps,
    -- The SIZE CODE the pack belongs to. It travels for the same reason type
    -- and grade do: an order line has to be able to say it was 'M2, 150 g -
    -- 200 g', and the size code id is what the stock hold is taken against.
    sc.id           AS size_code_id,
    sc.code         AS size_code,
    sc.meta         AS size_meta,
    a.total_grams,
    a.reserved_grams,
    a.sold_grams,
    a.status        AS availability_status
FROM product_pack_options u
JOIN product_size_codes sc ON sc.id = u.size_code_id
JOIN products p ON p.id = u.product_id
JOIN daily_availability a ON a.size_code_id = sc.id
    AND a.available_on = $1::date
WHERE u.is_active
  AND sc.is_active
  AND p.status = 'active'
  AND p.supplier_id = ANY($2::uuid[])
ORDER BY p.id, sc.sort_order, sc.created_at, u.sort_order, u.weight_grams
`

type ListInternalUnitsForDateParams struct {
	AvailableOn time.Time
	SupplierIds []uuid.UUID
}

type ListInternalUnitsForDateRow struct {
	UnitID             uuid.UUID
	Label              string
	WeightGrams        int32
	PricePaise         int64
	ProductID          uuid.UUID
	SupplierID         uuid.UUID
	ProductName        string
	ProductType        string
	Grade              *string
	MarkupBps          int32
	SizeCodeID         uuid.UUID
	SizeCode           string
	SizeMeta           *string
	TotalGrams         int32
	ReservedGrams      int32
	SoldGrams          int32
	AvailabilityStatus string
}

// ===========================================================================
// stock holds — CLAUDE.md §6.3
// ===========================================================================
// Everything vm-orders-api needs to price and validate a cart, for one day.
//
// Deliberately its own query rather than reusing ListCatalog. orders-api used
// to read the customer-facing /catalog endpoint, which was fine until prices
// split in two: that endpoint returns the CUSTOMER price and must never
// return the markup beside it, and orders-api needs both — the customer price
// to charge, the markup to know which part of it is not the grower's. Reading
// both from one row is also what stops the two drifting between calls.
//
// No paging: this is one day's produce from a handful of growers, and a cart
// can reference any of it.
func (q *Queries) ListInternalUnitsForDate(ctx context.Context, arg ListInternalUnitsForDateParams) ([]ListInternalUnitsForDateRow, error) {
	rows, err := q.db.Query(ctx, listInternalUnitsForDate, arg.AvailableOn, arg.SupplierIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInternalUnitsForDateRow{}
	for rows.Next() {
		var i ListInternalUnitsForDateRow
		if err := rows.Scan(
			&i.UnitID,
			&i.Label,
			&i.WeightGrams,
			&i.PricePaise,
			&i.ProductID,
			&i.SupplierID,
			&i.ProductName,
			&i.ProductType,
			&i.Grade,
			&i.MarkupBps,
			&i.SizeCodeID,
			&i.SizeCode,
			&i.SizeMeta,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.AvailabilityStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaForProducts = `-- name: ListMediaForProducts :many
SELECT m.id, m.product_id, m.kind, m.object_key, m.content_type, m.sort_order, m.created_at, m.size_code_id FROM product_media m
LEFT JOIN product_size_codes s ON s.id = m.size_code_id
WHERE m.product_id = ANY($1::uuid[])
ORDER BY m.product_id, (m.size_code_id IS NULL), s.sort_order, s.created_at,
         m.sort_order, m.created_at
`

// The galleries for a page of products, in one round trip. Ordered by product
// then size code so a caller can walk the rows and group them without a
// second sort.
//
// LEFT JOIN, because a row with a NULL size_code_id belongs to the whole
// product rather than to one grade. Those sort last within their product, so
// a caller appending them to each grade's gallery gets the grower's order for
// free — a grade's own pictures, then the farm.
func (q *Queries) ListMediaForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, listMediaForProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductMedium{}
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.ObjectKey,
			&i.ContentType,
			&i.SortOrder,
			&i.CreatedAt,
			&i.SizeCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaForSizeCode = `-- name: ListMediaForSizeCode :many
SELECT id, product_id, kind, object_key, content_type, sort_order, created_at, size_code_id FROM product_media
WHERE size_code_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListMediaForSizeCode(ctx context.Context, sizeCodeID *uuid.UUID) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, listMediaForSizeCode, sizeCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductMedium{}
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.ObjectKey,
			&i.ContentType,
			&i.SortOrder,
			&i.CreatedAt,
			&i.SizeCodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackOptionsForProduct = `-- name: ListPackOptionsForProduct :many
SELECT id, size_code_id, product_id, label, weight_grams, price_paise, is_active, sort_order, created_at, updated_at, meta FROM product_pack_options
WHERE product_id = $1
ORDER BY sort_order, weight_grams
`

func (q *Queries) ListPackOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductPackOption, error) {
	rows, err := q.db.Query(ctx, listPackOptionsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPackOption{}
	for rows.Next() {
		var i ProductPackOption
		if err := rows.Scan(
			&i.ID,
			&i.SizeCodeID,
			&i.ProductID,
			&i.Label,
			&i.WeightGrams,
			&i.PricePaise,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackOptionsForProducts = `-- name: ListPackOptionsForProducts :many
SELECT p.id, p.size_code_id, p.product_id, p.label, p.weight_grams, p.price_paise, p.is_active, p.sort_order, p.created_at, p.updated_at, p.meta FROM product_pack_options p
JOIN product_size_codes s ON s.id = p.size_code_id
WHERE p.product_id = ANY($1::uuid[])
ORDER BY p.product_id, s.sort_order, s.created_at, p.sort_order, p.weight_grams
`

// Every pack across a page of products, ordered so a caller can group by size
// code without a second sort.
func (q *Queries) ListPackOptionsForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductPackOption, error) {
	rows, err := q.db.Query(ctx, listPackOptionsForProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPackOption{}
	for rows.Next() {
		var i ProductPackOption
		if err := rows.Scan(
			&i.ID,
			&i.SizeCodeID,
			&i.ProductID,
			&i.Label,
			&i.WeightGrams,
			&i.PricePaise,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductIDsAfter = `-- name: ListProductIDsAfter :many
SELECT id, created_at FROM products
WHERE (created_at, id) > ($1::timestamptz, $2::uuid)
ORDER BY created_at, id
LIMIT $3
`

type ListProductIDsAfterParams struct {
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

type ListProductIDsAfterRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// The backfill's cursor: every product, oldest first, a page at a time.
func (q *Queries) ListProductIDsAfter(ctx context.Context, arg ListProductIDsAfterParams) ([]ListProductIDsAfterRow, error) {
	rows, err := q.db.Query(ctx, listProductIDsAfter, arg.AfterCreatedAt, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductIDsAfterRow{}
	for rows.Next() {
		var i ListProductIDsAfterRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps FROM products
WHERE ($3::uuid IS NULL OR supplier_id = $3::uuid)
  AND ($4::text   IS NULL OR type   = $4::text)
  AND ($5::text IS NULL OR status = $5::text)
  AND ($6::text IS NULL OR name ILIKE '%' || $6::text || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32
	Offset     int32
	SupplierID *uuid.UUID
	Type       *string
	Status     *string
	Search     *string
}

// Filters are all optional (sqlc.narg): a NULL means "no filter". Written as
// one query rather than assembled in Go, so there is no string concatenation
// anywhere near the SQL (rule 7).
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.SupplierID,
		arg.Type,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Name,
			&i.Type,
			&i.Grade,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MarkupBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSizeCodeAvailability = `-- name: ListSizeCodeAvailability :many
SELECT
    sc.id          AS size_code_id,
    sc.product_id,
    sc.code,
    sc.meta,
    sc.sort_order,
    -- Display only: decides how the grade's chip is drawn on the storefront.
    sc.harvest_share_pct,
    a.id           AS availability_id,
    a.total_grams,
    a.reserved_grams,
    a.sold_grams,
    a.status       AS availability_status
FROM product_size_codes sc
JOIN daily_availability a
     ON a.size_code_id = sc.id AND a.available_on = $1::date
WHERE sc.product_id = ANY($2::uuid[])
  AND sc.is_active
ORDER BY sc.product_id, sc.sort_order, sc.created_at
`

type ListSizeCodeAvailabilityParams struct {
	AvailableOn time.Time
	ProductIds  []uuid.UUID
}

type ListSizeCodeAvailabilityRow struct {
	SizeCodeID         uuid.UUID
	ProductID          uuid.UUID
	Code               string
	Meta               *string
	SortOrder          int32
	HarvestSharePct    *int16
	AvailabilityID     uuid.UUID
	TotalGrams         int32
	ReservedGrams      int32
	SoldGrams          int32
	AvailabilityStatus string
}

// Today's grades and their stock, for a page of products.
//
// The companion to ListCatalog: that query pages over products, this one fills
// in the grades each card and detail page offers. Ordered by the grower's own
// grade order so the client groups without sorting.
func (q *Queries) ListSizeCodeAvailability(ctx context.Context, arg ListSizeCodeAvailabilityParams) ([]ListSizeCodeAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listSizeCodeAvailability, arg.AvailableOn, arg.ProductIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSizeCodeAvailabilityRow{}
	for rows.Next() {
		var i ListSizeCodeAvailabilityRow
		if err := rows.Scan(
			&i.SizeCodeID,
			&i.ProductID,
			&i.Code,
			&i.Meta,
			&i.SortOrder,
			&i.HarvestSharePct,
			&i.AvailabilityID,
			&i.TotalGrams,
			&i.ReservedGrams,
			&i.SoldGrams,
			&i.AvailabilityStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSizeCodesForProduct = `-- name: ListSizeCodesForProduct :many
SELECT id, product_id, code, meta, is_active, sort_order, created_at, updated_at, harvest_share_pct FROM product_size_codes
WHERE product_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListSizeCodesForProduct(ctx context.Context, productID uuid.UUID) ([]ProductSizeCode, error) {
	rows, err := q.db.Query(ctx, listSizeCodesForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductSizeCode{}
	for rows.Next() {
		var i ProductSizeCode
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Meta,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HarvestSharePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSizeCodesForProducts = `-- name: ListSizeCodesForProducts :many
SELECT id, product_id, code, meta, is_active, sort_order, created_at, updated_at, harvest_share_pct FROM product_size_codes
WHERE product_id = ANY($1::uuid[])
ORDER BY product_id, sort_order, created_at
`

// Bulk fetch for the list view: one query for a whole page of products rather
// than N+1 round trips.
func (q *Queries) ListSizeCodesForProducts(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductSizeCode, error) {
	rows, err := q.db.Query(ctx, listSizeCodesForProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductSizeCode{}
	for rows.Next() {
		var i ProductSizeCode
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Code,
			&i.Meta,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HarvestSharePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailabilityForUpdate = `-- name: LockAvailabilityForUpdate :one
SELECT id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id FROM daily_availability
WHERE size_code_id = $1 AND available_on = $2
FOR UPDATE
`

type LockAvailabilityForUpdateParams struct {
	SizeCodeID  uuid.UUID
	AvailableOn time.Time
}

// Locks one availability row for update.
//
// The lock is now per SIZE CODE, which is what a gram pool belongs to: two
// customers buying different grades of the same produce no longer serialise
// against each other, and two buying the same grade still do.
//
// Callers MUST take these in a deterministic order (by size_code_id) across
// the whole request, or two concurrent checkouts touching the same two grades
// can deadlock by grabbing them in opposite orders.
func (q *Queries) LockAvailabilityForUpdate(ctx context.Context, arg LockAvailabilityForUpdateParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, lockAvailabilityForUpdate, arg.SizeCodeID, arg.AvailableOn)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const markCSVImportCommitted = `-- name: MarkCSVImportCommitted :one
UPDATE csv_imports
SET status = 'committed', committed_at = now()
WHERE id = $1 AND supplier_id = $2 AND status = 'preview'
RETURNING id, supplier_id, filename, status, total_rows, valid_rows, error_rows, report, created_at, committed_at
`

type MarkCSVImportCommittedParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// Filtered on status so a double-submit commits exactly once.
func (q *Queries) MarkCSVImportCommitted(ctx context.Context, arg MarkCSVImportCommittedParams) (CsvImport, error) {
	row := q.db.QueryRow(ctx, markCSVImportCommitted, arg.ID, arg.SupplierID)
	var i CsvImport
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Filename,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.ErrorRows,
		&i.Report,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const productExistsForSupplier = `-- name: ProductExistsForSupplier :one

SELECT EXISTS (
    SELECT 1 FROM products
    WHERE supplier_id = $1
      AND lower(btrim(name)) = lower(btrim($2::text))
      AND lower(coalesce(btrim(grade), '')) = lower(coalesce(btrim($3::text), ''))
      AND status <> 'archived'
) AS exists
`

type ProductExistsForSupplierParams struct {
	SupplierID uuid.UUID
	Name       string
	Grade      *string
}

// ===========================================================================
// development seed (mocks/)
// ===========================================================================
// The seed's idempotency check, in the same terms as the unique index
// products_supplier_name_grade_key: a live product of this name and grade.
func (q *Queries) ProductExistsForSupplier(ctx context.Context, arg ProductExistsForSupplierParams) (bool, error) {
	row := q.db.QueryRow(ctx, productExistsForSupplier, arg.SupplierID, arg.Name, arg.Grade)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const productImagesForIDs = `-- name: ProductImagesForIDs :many

SELECT DISTINCT ON (m.product_id)
    m.product_id AS id,
    m.object_key AS image_key
FROM product_media m
LEFT JOIN product_size_codes s ON s.id = m.size_code_id
WHERE m.product_id = ANY($1::uuid[]) AND m.kind = 'image'
ORDER BY m.product_id, (m.size_code_id IS NULL), s.sort_order, s.created_at,
         m.sort_order, m.created_at
`

type ProductImagesForIDsRow struct {
	ID       uuid.UUID
	ImageKey string
}

// ===========================================================================
// product_media
// ===========================================================================
// The cover photograph for products referenced by an order.
//
// Takes the FIRST size code's first image: an order line snapshots the pack it
// bought but not which grade's gallery to show, and the default grade is the
// one the storefront opens on.
//
// No status filter: an order placed months ago must still show its produce,
// and by then the product may well be archived. Order lines snapshot the name
// and price for exactly this reason (CLAUDE.md §5.3); the image is the one
// thing they cannot snapshot, because what is stored is an object key whose
// URL is minted at read time.
// A grade's own picture wins; the product-level gallery is the fallback, so a
// grower who only uploaded photographs of the farm still gets a thumbnail.
func (q *Queries) ProductImagesForIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductImagesForIDsRow, error) {
	rows, err := q.db.Query(ctx, productImagesForIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImagesForIDsRow{}
	for rows.Next() {
		var i ProductImagesForIDsRow
		if err := rows.Scan(&i.ID, &i.ImageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneProductEvents = `-- name: PruneProductEvents :execrows
DELETE FROM product_events_outbox WHERE created_at < $1
`

// Retention. CDC has already read these from the WAL.
func (q *Queries) PruneProductEvents(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneProductEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reopenAvailability = `-- name: ReopenAvailability :one
UPDATE daily_availability
SET status = 'open'
WHERE id = $1 AND supplier_id = $2 AND status = 'closed'
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type ReopenAvailabilityParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
}

// The deliberate counterpart to closing. Scoped to the owning supplier, and to
// rows that are actually closed, so a replay is a no-op rather than a silent
// success.
func (q *Queries) ReopenAvailability(ctx context.Context, arg ReopenAvailabilityParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, reopenAvailability, arg.ID, arg.SupplierID)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}

const setProductMarkup = `-- name: SetProductMarkup :one
UPDATE products SET markup_bps = $2
WHERE id = $1
RETURNING id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps
`

type SetProductMarkupParams struct {
	ID        uuid.UUID
	MarkupBps int32
}

// Sets the admin markup on a product. Admin only — a supplier must never be
// able to reach this, and never sees the column it writes.
//
// updated_at is deliberately NOT touched: it is the supplier's own signal for
// when their listing last changed, and moving it because we repriced would
// show a grower an edit they did not make.
func (q *Queries) SetProductMarkup(ctx context.Context, arg SetProductMarkupParams) (Product, error) {
	row := q.db.QueryRow(ctx, setProductMarkup, arg.ID, arg.MarkupBps)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const settleStockHold = `-- name: SettleStockHold :one
UPDATE stock_holds
SET status = $2, settled_at = now()
WHERE id = $1 AND status = 'held'
RETURNING id, order_ref, product_id, available_on, grams, status, expires_at, created_at, settled_at, size_code_id
`

type SettleStockHoldParams struct {
	ID     uuid.UUID
	Status string
}

// Filtered on status so a double release or commit is a no-op rather than
// double-counting grams.
func (q *Queries) SettleStockHold(ctx context.Context, arg SettleStockHoldParams) (StockHold, error) {
	row := q.db.QueryRow(ctx, settleStockHold, arg.ID, arg.Status)
	var i StockHold
	err := row.Scan(
		&i.ID,
		&i.OrderRef,
		&i.ProductID,
		&i.AvailableOn,
		&i.Grams,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SettledAt,
		&i.SizeCodeID,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    name        = $3,
    type        = $4,
    grade       = $5,
    description = $6,
    status      = $7
WHERE id = $1 AND supplier_id = $2
RETURNING id, supplier_id, name, type, grade, description, status, created_at, updated_at, markup_bps
`

type UpdateProductParams struct {
	ID          uuid.UUID
	SupplierID  uuid.UUID
	Name        string
	Type        string
	Grade       *string
	Description *string
	Status      string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.SupplierID,
		arg.Name,
		arg.Type,
		arg.Grade,
		arg.Description,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Name,
		&i.Type,
		&i.Grade,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MarkupBps,
	)
	return i, err
}

const upsertAvailability = `-- name: UpsertAvailability :one
INSERT INTO daily_availability (
    supplier_id, product_id, size_code_id, available_on, total_grams, status
)
VALUES ($1, $2, $3, $4, $5, 'open')
ON CONFLICT (size_code_id, available_on) DO UPDATE
SET total_grams = EXCLUDED.total_grams
RETURNING id, supplier_id, product_id, available_on, total_grams, reserved_grams, sold_grams, status, created_at, updated_at, size_code_id
`

type UpsertAvailabilityParams struct {
	SupplierID  uuid.UUID
	ProductID   uuid.UUID
	SizeCodeID  uuid.UUID
	AvailableOn time.Time
	TotalGrams  int32
}

// Upsert: re-declaring a product for the same day updates it rather than
// failing on the (product_id, available_on) unique constraint.
// Reserved and sold are never touched here — they belong to the order flow.
// Updating the declared quantity must NOT reopen a closed product.
//
// This previously forced status='open' on every conflict. Because the supplier
// screen submits every row it has a number for, editing one product silently
// reopened every other product the supplier had closed that day — stock they
// had deliberately stopped selling went back on sale. Reopening is now its own
// explicit action below. New rows still start open.
func (q *Queries) UpsertAvailability(ctx context.Context, arg UpsertAvailabilityParams) (DailyAvailability, error) {
	row := q.db.QueryRow(ctx, upsertAvailability,
		arg.SupplierID,
		arg.ProductID,
		arg.SizeCodeID,
		arg.AvailableOn,
		arg.TotalGrams,
	)
	var i DailyAvailability
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.ProductID,
		&i.AvailableOn,
		&i.TotalGrams,
		&i.ReservedGrams,
		&i.SoldGrams,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SizeCodeID,
	)
	return i, err
}
