// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type DeadLetterEvent struct {
	EventID     uuid.UUID
	SourceTable string
	EventType   *string
	Payload     []byte
	Error       string
	Lsn         string
	ReceivedAt  time.Time
}

type Order struct {
	OrderID              uuid.UUID
	OrderNumber          string
	CustomerID           uuid.UUID
	ScheduleID           *uuid.UUID
	Source               string
	Status               string
	PaymentMethod        *string
	PaidVia              *string
	SubtotalPaise        int64
	PlatformFeePaise     int64
	DeliveryFeePaise     int64
	TotalPaise           int64
	MarkupPaise          int64
	SupplierPayablePaise *int64
	ItemCount            int32
	TotalQty             int32
	TotalGrams           int64
	PlacedAt             time.Time
	PaidAt               *time.Time
	ProcessedAt          *time.Time
	DispatchedAt         *time.Time
	CancelledAt          *time.Time
	ExpiredAt            *time.Time
	RefundedAt           *time.Time
	CancelledFromStatus  *string
	PlacedDateIst        time.Time
	PlacedHourIst        int16
	PlacedBeforeCutoff   bool
	ProcessingAt         time.Time
	DeliveryDay          time.Time
	ExpectedDeliveryDate time.Time
	ShipCity             *string
	ShipState            *string
	ShipPincode          *string
	LastEventID          uuid.UUID
	LastEventType        string
	LastEventAt          time.Time
	UpdatedAt            time.Time
}

type OrderItem struct {
	OrderItemID     uuid.UUID
	OrderID         uuid.UUID
	SupplierID      uuid.UUID
	ProductID       uuid.UUID
	SizeCodeID      *uuid.UUID
	PackOptionID    uuid.UUID
	ProductName     string
	ProductType     *string
	Grade           *string
	SizeCode        *string
	PackLabel       string
	WeightGrams     int32
	Qty             int32
	UnitPricePaise  int64
	LineTotalPaise  int64
	LineMarkupPaise int64
	LineGrams       int64
}

type ProcessedEvent struct {
	EventID     uuid.UUID
	SourceTable string
	Lsn         string
	ProcessedAt time.Time
}

type Product struct {
	ProductID       uuid.UUID
	SupplierID      uuid.UUID
	Name            string
	Type            string
	Grade           *string
	Status          string
	MarkupBps       int32
	Source          string
	SizeCodeCount   int32
	PackCount       int32
	ActivePackCount int32
	MinPricePaise   *int64
	MaxPricePaise   *int64
	ImageCount      int32
	VideoCount      int32
	CreatedAt       time.Time
	FirstActiveAt   *time.Time
	ArchivedAt      *time.Time
	LastEventID     uuid.UUID
	LastEventType   string
	LastEventAt     time.Time
	UpdatedAt       time.Time
}

type ProductPack struct {
	PackOptionID       uuid.UUID
	ValidFrom          time.Time
	ValidTo            *time.Time
	ProductID          uuid.UUID
	SizeCodeID         uuid.UUID
	SizeCode           string
	SizeMeta           *string
	HarvestSharePct    *int16
	SizeCodeActive     bool
	Label              string
	WeightGrams        int32
	PricePaise         int64
	MarkupBps          int32
	CustomerPricePaise int64
	IsActive           bool
}

type Supplier struct {
	SupplierID    uuid.UUID
	BusinessName  string
	Status        string
	City          *string
	State         *string
	Pincode       *string
	GstRegistered bool
	CommissionBps *int32
	CreatedAt     time.Time
	ApprovedAt    *time.Time
	SuspendedAt   *time.Time
	LastEventID   uuid.UUID
	LastEventType string
	LastEventAt   time.Time
	UpdatedAt     time.Time
}

type VCurrentPack struct {
	PackOptionID       uuid.UUID
	ValidFrom          time.Time
	ValidTo            *time.Time
	ProductID          uuid.UUID
	SizeCodeID         uuid.UUID
	SizeCode           string
	SizeMeta           *string
	HarvestSharePct    *int16
	SizeCodeActive     bool
	Label              string
	WeightGrams        int32
	PricePaise         int64
	MarkupBps          int32
	CustomerPricePaise int64
	IsActive           bool
}

type VOrderLine struct {
	OrderItemID        uuid.UUID
	OrderID            uuid.UUID
	SupplierID         uuid.UUID
	ProductID          uuid.UUID
	SizeCodeID         *uuid.UUID
	PackOptionID       uuid.UUID
	ProductName        string
	ProductType        *string
	Grade              *string
	SizeCode           *string
	PackLabel          string
	WeightGrams        int32
	Qty                int32
	UnitPricePaise     int64
	LineTotalPaise     int64
	LineMarkupPaise    int64
	LineGrams          int64
	OrderNumber        string
	CustomerID         uuid.UUID
	Status             string
	Source             string
	PaymentMethod      *string
	PlacedAt           time.Time
	PaidAt             *time.Time
	PlacedDateIst      time.Time
	PlacedBeforeCutoff bool
	ShipCity           *string
	ShipState          *string
	ShipPincode        *string
	SupplierName       *string
}
