// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Queries for the analytics projections (CLAUDE.md §5.4).
	//
	// Every write here is idempotent under replay: an upsert keyed on the
	// aggregate, guarded so a STALE event (older than what the row already
	// reflects) cannot roll it back.
	// ===========================================================================
	// bookkeeping
	// ===========================================================================
	// Returns a row only the FIRST time an event id is seen.
	ClaimEvent(ctx context.Context, arg ClaimEventParams) (uuid.UUID, error)
	ClosePack(ctx context.Context, arg ClosePackParams) error
	CurrentPacksForProduct(ctx context.Context, productID uuid.UUID) ([]ProductPack, error)
	DeadLetter(ctx context.Context, arg DeadLetterParams) error
	// Two versions of one pack at the same instant (two events in one source
	// transaction) collapse into the later one rather than violating the key.
	OpenPack(ctx context.Context, arg OpenPackParams) error
	PruneProcessedEvents(ctx context.Context, processedAt time.Time) (int64, error)
	// ===========================================================================
	// orders
	// ===========================================================================
	// Lifecycle timestamps are never cleared and never moved: COALESCE keeps the
	// first time a transition was seen. The WHERE makes a stale event a no-op.
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) (int64, error)
	// Lines never change after placement, but an upsert costs nothing and means a
	// snapshot can repair a line written by an older consumer.
	UpsertOrderItem(ctx context.Context, arg UpsertOrderItemParams) error
	// ===========================================================================
	// products
	// ===========================================================================
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (int64, error)
	// ===========================================================================
	// suppliers
	// ===========================================================================
	// approved_at and suspended_at keep the first time each was seen; a later
	// event never clears them. The WHERE makes a stale event a no-op.
	UpsertSupplier(ctx context.Context, arg UpsertSupplierParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
