// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type AdminAuditLog struct {
	ID          uuid.UUID
	AdminUserID uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	Before      []byte
	After       []byte
	CreatedAt   time.Time
}

type Cart struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CartItem struct {
	ID            uuid.UUID
	CartID        uuid.UUID
	ProductUnitID uuid.UUID
	ProductID     uuid.UUID
	SupplierID    uuid.UUID
	Qty           int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// One row per IST day whose courier report has been emailed. The primary key is the send-once guard.
type DailyReportSend struct {
	ReportDate time.Time
	SentAt     time.Time
	OrderCount int32
	Recipients string
}

type Order struct {
	ID                   uuid.UUID
	OrderNumber          string
	CustomerID           uuid.UUID
	Status               string
	AddressSnapshot      []byte
	SubtotalPaise        int64
	PlatformFeePaise     int64
	DeliveryFeePaise     int64
	TotalPaise           int64
	PlacedAt             time.Time
	ProcessingAt         time.Time
	DeliveryDay          time.Time
	ExpectedDeliveryDate time.Time
	PaymentStatus        string
	RazorpayOrderID      *string
	RazorpayPaymentID    *string
	CancelledAt          *time.Time
	CancelReason         *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ScheduleID           *uuid.UUID
}

type OrderEventsOutbox struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	EventType     string
	SchemaVersion int16
	OccurredAt    time.Time
	ActorRole     string
	RequestID     *string
	Payload       []byte
	CreatedAt     time.Time
}

type OrderIdempotency struct {
	Key        string
	CustomerID uuid.UUID
	OrderID    uuid.UUID
	CreatedAt  time.Time
}

type OrderItem struct {
	ID                  uuid.UUID
	OrderID             uuid.UUID
	SupplierID          uuid.UUID
	ProductID           uuid.UUID
	ProductUnitID       uuid.UUID
	ProductNameSnapshot string
	UnitLabelSnapshot   string
	GradeSnapshot       *string
	WeightGrams         int32
	UnitPricePaise      int64
	Qty                 int32
	LineTotalPaise      int64
	CreatedAt           time.Time
	// Admin markup per pack, included in unit_price_paise. Never paid to the supplier.
	MarkupPaise int64
	// markup_paise * qty. Subtract from line_total_paise for the supplier's share.
	LineMarkupPaise int64
	// The markup rate applied to this line, in basis points. markup_paise is the amount it produced.
	MarkupBps int32
	// Produce category as it was when sold (fruit/vegetable/microgreen/other). NULL on lines written before the column existed.
	ProductTypeSnapshot *string
	// catalog.product_size_codes(id). No FK by design — different schema.
	SizeCodeID *uuid.UUID
	// The grade code as it read when the order was placed, e.g. 'M2'. NULL for pre-grade orders.
	SizeCodeSnapshot *string
	// The grade's detail line as it read then, e.g. '150 g - 200 g'.
	SizeMetaSnapshot *string
}

type Outbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	LastError     *string
}

type Payment struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	Provider          string
	ProviderOrderID   *string
	ProviderPaymentID *string
	AmountPaise       int64
	Status            string
	Method            *string
	RawPayload        []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Schedule struct {
	ID               uuid.UUID
	CustomerID       uuid.UUID
	AddressID        uuid.UUID
	AddressSnapshot  []byte
	Frequency        string
	Weekdays         []int16
	DayOfMonth       *int16
	StartDate        time.Time
	EndDate          *time.Time
	NextDeliveryDate *time.Time
	Status           string
	LowBalanceSkips  int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ScheduleItem struct {
	ID                  uuid.UUID
	ScheduleID          uuid.UUID
	ProductID           uuid.UUID
	ProductUnitID       uuid.UUID
	Qty                 int32
	ProductNameSnapshot string
	UnitLabelSnapshot   string
	SizeCodeSnapshot    *string
	CreatedAt           time.Time
}

type ScheduleOccurrence struct {
	ID           uuid.UUID
	ScheduleID   uuid.UUID
	DeliveryDate time.Time
	Status       string
	OrderID      *uuid.UUID
	Note         *string
	CreatedAt    time.Time
}

type StockReservation struct {
	ID                   uuid.UUID
	OrderID              uuid.UUID
	ProductID            uuid.UUID
	CatalogReservationID uuid.UUID
	AvailableOn          time.Time
	Grams                int32
	Status               string
	ExpiresAt            time.Time
	CreatedAt            time.Time
}

type SupplierPayout struct {
	ID           uuid.UUID
	SupplierID   uuid.UUID
	OrderID      uuid.UUID
	AmountPaise  int64
	Status       string
	MarkedPaidBy *uuid.UUID
	MarkedPaidAt *time.Time
	ReferenceNo  *string
	Notes        *string
	CreatedAt    time.Time
}

type Wallet struct {
	CustomerID   uuid.UUID
	BalancePaise int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type WalletRefund struct {
	ID               uuid.UUID
	CustomerID       uuid.UUID
	TopupID          uuid.UUID
	AmountPaise      int64
	Status           string
	RazorpayRefundID *string
	AdminUserID      uuid.UUID
	Notes            *string
	Error            *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WalletTopup struct {
	ID                uuid.UUID
	CustomerID        uuid.UUID
	AmountPaise       int64
	Status            string
	RazorpayOrderID   *string
	RazorpayPaymentID *string
	RefundedPaise     int64
	IdempotencyKey    string
	CapturedAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type WalletTransaction struct {
	ID                uuid.UUID
	CustomerID        uuid.UUID
	Kind              string
	AmountPaise       int64
	BalanceAfterPaise int64
	TopupID           *uuid.UUID
	OrderID           *uuid.UUID
	RefundID          *uuid.UUID
	CreatedAt         time.Time
}

type WebhookEvent struct {
	ID              uuid.UUID
	Provider        string
	ProviderEventID string
	EventType       string
	Payload         []byte
	ReceivedAt      time.Time
	ProcessedAt     *time.Time
	Error           *string
	Attempts        int32
}
