// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddTopupRefunded(ctx context.Context, arg AddTopupRefundedParams) (WalletTopup, error)
	AdminBulkMarkDispatched(ctx context.Context, dollar_1 []uuid.UUID) ([]Order, error)
	// Bulk processing. Returns only the rows it actually moved, so the caller can
	// report "12 of 15 processed" rather than claiming all of them.
	AdminBulkMarkProcessed(ctx context.Context, dollar_1 []uuid.UUID) ([]Order, error)
	AdminCancelOrder(ctx context.Context, arg AdminCancelOrderParams) (Order, error)
	AdminCountOrders(ctx context.Context, arg AdminCountOrdersParams) (int64, error)
	AdminDispatchAllProcessed(ctx context.Context, arg AdminDispatchAllProcessedParams) ([]Order, error)
	// ===========================================================================
	// admin: orders
	// ===========================================================================
	// Every filter is optional (sqlc.narg). Written as one statement rather than
	// assembled in Go, so no string concatenation goes near the SQL (rule 7).
	AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]Order, error)
	// Admin: every wallet holding money, largest first.
	AdminListWallets(ctx context.Context, arg AdminListWalletsParams) ([]AdminListWalletsRow, error)
	// Manual transition to dispatched. Filtered on the only legal predecessor, so
	// an unpaid or cancelled order cannot be dispatched.
	AdminMarkOrderDispatched(ctx context.Context, id uuid.UUID) (Order, error)
	// ---------------------------------------------------------------------------
	// Fulfilment transitions: paid -> processed -> dispatched.
	//
	// Every one filters on its only legal predecessor inside the UPDATE. That is
	// the concurrency guard as well as the state machine: two admins clicking at
	// once cannot both "win", and a bulk action cannot skip a step by including an
	// id that is not ready.
	// ---------------------------------------------------------------------------
	AdminMarkOrderProcessed(ctx context.Context, id uuid.UUID) (Order, error)
	// The courier handover sheet.
	//
	// Everything needed to put a parcel on a van, in one row per order: who it
	// goes to, where, and what is in it. The address is the SNAPSHOT taken at
	// placement, never the customer's current address book — a customer editing
	// their address after ordering must not silently redirect a parcel already
	// being packed.
	AdminOrdersForExport(ctx context.Context, arg AdminOrdersForExportParams) ([]AdminOrdersForExportRow, error)
	// Every paid order in a window. Used by "process all" and by the scheduled
	// job; both mean the same thing, one is a click and one is a clock.
	AdminProcessAllPaid(ctx context.Context, arg AdminProcessAllPaidParams) ([]Order, error)
	AdminWalletTotals(ctx context.Context) (AdminWalletTotalsRow, error)
	// Basket shape and who is buying: the two figures that say whether a period
	// grew because more people came or because they bought more.
	//
	// `returning_customers` counts customers with an EARLIER paid order outside
	// the window, so "new" means new to us, not new to this period.
	AnalyticsBasketAndCustomers(ctx context.Context, arg AnalyticsBasketAndCustomersParams) (AnalyticsBasketAndCustomersRow, error)
	// Orders either side of the 4pm IST cutoff (CLAUDE.md §6.1).
	//
	// The hour is a parameter rather than a literal 16 so this reads whatever
	// ORDER_CUTOFF_HOUR_IST is configured to — a query that hardcoded 16 would
	// quietly start lying the day the cutoff moves.
	AnalyticsCutoffSplit(ctx context.Context, arg AnalyticsCutoffSplitParams) (AnalyticsCutoffSplitRow, error)
	// One row per calendar day in the window that had any order at all.
	//
	// Days with no orders are absent rather than zero: filling the gaps needs a
	// date series, and the caller already knows the window's bounds, so it can do
	// that without a second table scan.
	AnalyticsDailyTrend(ctx context.Context, arg AnalyticsDailyTrendParams) ([]AnalyticsDailyTrendRow, error)
	// What happened to the orders placed in the window, by outcome.
	//
	// Counts every order PLACED in the period whatever its state, unlike the
	// other analytics queries: the whole point is the ones that did not become
	// revenue. `expired` and `payment_failed` are checkout falling over;
	// `cancelled` is a decision someone made afterwards.
	AnalyticsOrderOutcomes(ctx context.Context, arg AnalyticsOrderOutcomesParams) ([]AnalyticsOrderOutcomesRow, error)
	// Revenue by produce. Snapshots, so an edited, archived or deleted product
	// still reports under the name it was sold as.
	AnalyticsRevenueByProduce(ctx context.Context, arg AnalyticsRevenueByProduceParams) ([]AnalyticsRevenueByProduceRow, error)
	// Which GRADES the platform actually sells, across every supplier.
	//
	// The supplier's own Insights tab answers this for one grower; this is the
	// same question for the shop. It is what says whether the market wants XL2 or
	// whether growers are picking a grade nobody buys — and neither the produce
	// breakdown (which sums the grades) nor the pack breakdown (box sizes, the
	// same across grades) can answer it.
	//
	// Grouped by produce AND grade, never grade alone: one supplier's M2
	// pomegranate and another's M2 tomato are different goods, and a row reading
	// "M2" that summed them would be worse than no row. Ungraded lines are
	// excluded rather than bucketed — size_code_snapshot is NULL on an ungraded
	// listing and on any order predating size codes (§5.3).
	AnalyticsRevenueBySizeCode(ctx context.Context, arg AnalyticsRevenueBySizeCodeParams) ([]AnalyticsRevenueBySizeCodeRow, error)
	// ===========================================================================
	// admin analytics — the dashboard's breakdowns
	//
	// Every query below is scoped by the SAME window the dashboard tiles use:
	// `(o.placed_at AT TIME ZONE 'Asia/Kolkata')::date BETWEEN $1 AND $2`, on
	// placed_at, over the paid statuses. Sharing one basis is what lets the
	// screen claim its totals reconcile with each other — a breakdown filtered on
	// a different column, or a different status set, would add up to a number the
	// tile above it does not show.
	//
	// "Revenue" here is what the CUSTOMER paid for those lines (line_total_paise,
	// which includes our markup), not what the grower is owed. The grower's share
	// and our margin are reported beside it rather than folded into one figure.
	// ===========================================================================
	// Revenue by supplier, with what we actually kept from each.
	//
	// margin = what customers paid for their lines − what their payout pays them.
	// Read from the payout rows rather than recomputed from a commission rate:
	// rates are per-supplier and negotiable, so a rate-based figure would be
	// describing a policy rather than what happened (the same reasoning as
	// CommissionCollectedInRange).
	AnalyticsRevenueBySupplier(ctx context.Context, arg AnalyticsRevenueBySupplierParams) ([]AnalyticsRevenueBySupplierRow, error)
	// Where the parcels are going, from the address SNAPSHOT on the order — the
	// address as it was when placed, which is where it was actually sent, even if
	// the customer has since edited or deleted it.
	AnalyticsTopDestinations(ctx context.Context, arg AnalyticsTopDestinationsParams) ([]AnalyticsTopDestinationsRow, error)
	// Filtered on status='created' inside the UPDATE, so it is the replay guard as
	// well as the transition: two captures of one top-up cannot both credit.
	CaptureWalletTopup(ctx context.Context, arg CaptureWalletTopupParams) (WalletTopup, error)
	// ===========================================================================
	// daily courier report
	// ===========================================================================
	// Claims the right to send today's report.
	//
	// ON CONFLICT DO NOTHING means the second caller gets no row back, which is
	// how a replica — or the next tick a minute later — learns that someone else
	// already sent it. The same shape as the webhook dedupe: the constraint does
	// the thinking, not the application.
	ClaimDailyReport(ctx context.Context, arg ClaimDailyReportParams) (DailyReportSend, error)
	// The sweeper's claim. SKIP LOCKED lets replicas sweep in parallel without
	// contending for the same rows.
	//
	// A hold whose order Razorpay has reported CAPTURED is never claimed, however
	// long it has lapsed. The webhook event is recorded before it is processed, so
	// a capture whose processing failed (a database blip, an amount mismatch) still
	// shows here while the order sits in pending_payment. Releasing that stock
	// would sell a paying customer's produce to someone else; holding it until an
	// admin records the payment or refunds it costs only grams.
	//
	// And a hold whose order went to Razorpay is claimed only once the sweeper has
	// ASKED Razorpay and been told no money was taken (`cleared`, from
	// ListLapsedRazorpayOrders). That covers the capture whose webhook has not
	// arrived at all yet — an outage, a backlog — which leaves no row above to
	// find. An order that never reached Razorpay has nothing to ask about.
	ClaimExpiredReservations(ctx context.Context, arg ClaimExpiredReservationsParams) ([]StockReservation, error)
	// ===========================================================================
	// idempotency — CLAUDE.md rule 6
	// ===========================================================================
	// The unique constraint IS the guard. A replayed key collides, and the handler
	// returns the original order instead of charging twice.
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (OrderIdempotency, error)
	// The dispatch counterpart of ClaimOrdersDueForProcessing: everything whose
	// delivery day has arrived and which nobody dispatched by hand.
	//
	// `delivery_day` is a DATE, and today's IST date arrives as a PARAMETER rather
	// than being computed here with `AT TIME ZONE`. That keeps the one definition
	// of "today" in Go, where isttime owns it and tests cover it (CLAUDE.md rule 2)
	// — a second copy in SQL would also depend on the database's own tzdata.
	//
	// `<=` rather than `=` so an order whose day passed while the service was down
	// is still picked up, exactly as the processing job self-heals.
	//
	// Filtered to 'processed': an order still awaiting payment, or cancelled, must
	// never be dispatched by a clock.
	ClaimOrdersDueForDispatch(ctx context.Context, arg ClaimOrdersDueForDispatchParams) ([]Order, error)
	// The scheduled job's claim. An order becomes due at its OWN processing_at,
	// which is 4pm IST of its processing date (CLAUDE.md §6.1) — so this is what
	// "process everything at 4pm" actually means, and it self-heals: an order that
	// became due while the service was restarting is picked up on the next tick
	// rather than missed forever.
	ClaimOrdersDueForProcessing(ctx context.Context, limit int32) ([]Order, error)
	// ===========================================================================
	// outbox dispatcher
	// ===========================================================================
	// SKIP LOCKED so several dispatcher replicas can drain the queue in parallel.
	ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error)
	ClearCart(ctx context.Context, cartID uuid.UUID) (int64, error)
	// Commission actually collected in a period.
	//
	// Derived from what happened, not recomputed from a rate. Supplier commission
	// is now per-supplier, so applying the platform rate to the total subtotal
	// gives a number that is wrong for every grower on a negotiated rate — and
	// wrong in a way nobody would notice, because it still looks plausible.
	//
	// supplier_payouts stores the NET amount a grower receives, so the difference
	// between their line totals and their payout IS the commission, whatever rate
	// produced it. It also stays correct if a rate changes after the fact, because
	// the payout row was written at the rate that applied at the time.
	// Supplier gross is the ORDER SUBTOTAL MINUS THE MARKUP, not the subtotal.
	//
	// The subtotal is what the customer paid, and part of that is our markup — it
	// was never the grower's to be commissioned on. Left as subtotal_paise, this
	// reported commission = gross - payouts, and the markup fell inside that
	// difference: every rupee of markup would have been counted a second time,
	// once here and once as markup revenue.
	CommissionCollectedInRange(ctx context.Context, arg CommissionCollectedInRangeParams) (CommissionCollectedInRangeRow, error)
	CountOrdersForCustomer(ctx context.Context, customerID uuid.UUID) (int64, error)
	// Serial per IST day, for the human-friendly VM-YYMMDD-NNNN number.
	CountOrdersPlacedOn(ctx context.Context, placedAt time.Time) (int64, error)
	// How many rows the suppression above would affect. Run first, and read it.
	CountUnsentOutbox(ctx context.Context, createdAt time.Time) (int64, error)
	CountWalletTransactions(ctx context.Context, customerID uuid.UUID) (int64, error)
	CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (ScheduleOccurrence, error)
	// ===========================================================================
	// orders
	// ===========================================================================
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// unit_price_paise and line_total_paise are what the CUSTOMER paid; the markup
	// columns record which part of that was ours, and at what rate. Subtracting is
	// what keeps a grower's payout on their own price (CLAUDE.md §6.2).
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	// ===========================================================================
	// payments, webhook events, payouts — CLAUDE.md §6.4
	// ===========================================================================
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// ===========================================================================
	// Schedules — CLAUDE.md §6.7
	// ===========================================================================
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateScheduleItem(ctx context.Context, arg CreateScheduleItemParams) (ScheduleItem, error)
	// ===========================================================================
	// stock_reservations (orders-side mirror of catalog holds)
	// ===========================================================================
	CreateStockReservation(ctx context.Context, arg CreateStockReservationParams) (StockReservation, error)
	// One row per (order, supplier). The unique constraint makes payout creation
	// idempotent: a replayed capture cannot double-pay a supplier.
	CreateSupplierPayout(ctx context.Context, arg CreateSupplierPayoutParams) (SupplierPayout, error)
	// A wallet-paid order's payment row. provider = 'wallet' is how every
	// report tells it apart from a card payment.
	CreateWalletPayment(ctx context.Context, arg CreateWalletPaymentParams) (Payment, error)
	CreateWalletRefund(ctx context.Context, arg CreateWalletRefundParams) (WalletRefund, error)
	CreateWalletTopup(ctx context.Context, arg CreateWalletTopupParams) (WalletTopup, error)
	DashboardOutstanding(ctx context.Context) (int64, error)
	// ===========================================================================
	// admin: dashboard
	// ===========================================================================
	// Today's trading figures, in IST. GMV counts only orders that were actually
	// paid — a pending_payment order is not revenue.
	// Trading figures over an IST date range, inclusive of both ends.
	//
	// The range is compared against placed_at converted to Asia/Kolkata, not to
	// the server's zone: a business day here is an IST calendar day (CLAUDE.md
	// rule 2), and an order placed at 11pm IST belongs to that day even though it
	// is already tomorrow in UTC.
	//
	// Note this is `BETWEEN $1 AND $2` — passing the same date twice gives a
	// single day, which is how "Today" is served without a second query.
	DashboardRange(ctx context.Context, arg DashboardRangeParams) (DashboardRangeRow, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	// Only a customer's own skip can be undone.
	DeleteCustomerSkip(ctx context.Context, arg DeleteCustomerSkipParams) (int64, error)
	DeleteScheduleItems(ctx context.Context, scheduleID uuid.UUID) error
	// ===========================================================================
	// outbox
	// ===========================================================================
	EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (Outbox, error)
	// ===========================================================================
	// Wallet — CLAUDE.md §6.7
	// ===========================================================================
	// Creates the wallet on first touch. DO UPDATE rather than DO NOTHING so the
	// row comes back either way.
	EnsureWallet(ctx context.Context, customerID uuid.UUID) (Wallet, error)
	// Expires an order whose held stock has lapsed.
	//
	// Filtered on pending_payment, and that filter is the whole point. The sweeper
	// used to call SetOrderStatus, which has no guard, so a payment that committed
	// while the sweep was in flight could be overwritten with 'expired' — money
	// captured, stock released, order dead. Every other transition in this file is
	// filtered on its only legal predecessor (see MarkOrderPaid); this one was the
	// exception.
	//
	// Zero rows updated means the order moved on while we were working, which is
	// not an error: the reservation rows have already been released, and an order
	// that reached 'paid' has its own committed reservations.
	ExpireOrderIfUnpaid(ctx context.Context, id uuid.UUID) (int64, error)
	GetOccurrence(ctx context.Context, arg GetOccurrenceParams) (ScheduleOccurrence, error)
	// Queries for vm-orders-api. Generated into Go by sqlc (CLAUDE.md §3).
	//
	// Ownership rule: every customer-facing query takes customer_id and filters on
	// it IN SQL, so one customer's cart or order is never returned to another.
	// ===========================================================================
	// carts
	// ===========================================================================
	// One live cart per customer; the upsert makes "get or create" a single round
	// trip with no race between two tabs.
	GetOrCreateCart(ctx context.Context, customerID uuid.UUID) (Cart, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByRazorpayOrderID(ctx context.Context, razorpayOrderID *string) (Order, error)
	// Ownership is the WHERE clause, not a later check.
	GetOrderForCustomer(ctx context.Context, arg GetOrderForCustomerParams) (Order, error)
	GetPaymentForOrder(ctx context.Context, orderID uuid.UUID) (Payment, error)
	// For the outbox, which has only the schedule id.
	GetScheduleByID(ctx context.Context, id uuid.UUID) (Schedule, error)
	// Ownership is the WHERE clause.
	GetScheduleForCustomer(ctx context.Context, arg GetScheduleForCustomerParams) (Schedule, error)
	GetWallet(ctx context.Context, customerID uuid.UUID) (Wallet, error)
	GetWalletTopupByKey(ctx context.Context, arg GetWalletTopupByKeyParams) (WalletTopup, error)
	GetWalletTopupByRazorpayOrderID(ctx context.Context, razorpayOrderID *string) (WalletTopup, error)
	GetWalletTopupForCustomer(ctx context.Context, arg GetWalletTopupForCustomerParams) (WalletTopup, error)
	GetWebhookEvent(ctx context.Context, providerEventID string) (WebhookEvent, error)
	// ===========================================================================
	// admin audit — CLAUDE.md §5.3
	// ===========================================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AdminAuditLog, error)
	// ===========================================================================
	// analytics order events — CLAUDE.md §5.4
	// ===========================================================================
	// Written in the caller's transaction, next to the transition it describes.
	InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) (uuid.UUID, error)
	InsertWalletTransaction(ctx context.Context, arg InsertWalletTransactionParams) (WalletTransaction, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AdminAuditLog, error)
	ListCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	// Everything the charging run must look at today: the date being charged,
	// and any earlier date it never reached. customer_id narrows it to one
	// customer — for tests against a shared database, and for an operator
	// re-running one account by hand.
	ListDueSchedules(ctx context.Context, arg ListDueSchedulesParams) ([]Schedule, error)
	// The customer's future skips, to mark on the upcoming-dates list.
	ListFutureSkips(ctx context.Context, arg ListFutureSkipsParams) ([]time.Time, error)
	// Held reservations for an order, LOCKED.
	//
	// FOR UPDATE so the payment transaction owns these rows before it commits them.
	// The sweeper claims expired reservations with SKIP LOCKED, so it steps around
	// an order being paid for rather than racing it to the order's status column.
	ListHeldReservationsForOrder(ctx context.Context, orderID uuid.UUID) ([]StockReservation, error)
	// The orders the sweeper must check with Razorpay before it may claim their
	// lapsed holds: those that went to Razorpay and have no recorded capture
	// (one with a capture is held regardless, so asking would be a wasted call).
	// Oldest first, the order the claim works in.
	ListLapsedRazorpayOrders(ctx context.Context, limit int32) ([]ListLapsedRazorpayOrdersRow, error)
	ListOccurrencesForSchedule(ctx context.Context, scheduleID uuid.UUID) ([]ListOccurrencesForScheduleRow, error)
	// The backfill's cursor: every order, oldest first, a page at a time.
	ListOrderIDsAfter(ctx context.Context, arg ListOrderIDsAfterParams) ([]ListOrderIDsAfterRow, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrderItemsForOrders(ctx context.Context, dollar_1 []uuid.UUID) ([]OrderItem, error)
	ListOrdersForCustomer(ctx context.Context, arg ListOrdersForCustomerParams) ([]Order, error)
	ListPayouts(ctx context.Context, arg ListPayoutsParams) ([]ListPayoutsRow, error)
	ListPayoutsForOrder(ctx context.Context, orderID uuid.UUID) ([]SupplierPayout, error)
	ListReservationsForOrder(ctx context.Context, orderID uuid.UUID) ([]StockReservation, error)
	ListScheduleItems(ctx context.Context, scheduleID uuid.UUID) ([]ScheduleItem, error)
	ListScheduleItemsForSchedules(ctx context.Context, ids []uuid.UUID) ([]ScheduleItem, error)
	ListSchedulesForCustomer(ctx context.Context, customerID uuid.UUID) ([]Schedule, error)
	ListWalletRefundsForCustomer(ctx context.Context, customerID uuid.UUID) ([]WalletRefund, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]ListWalletTransactionsRow, error)
	// Locks the requested payouts so two admins cannot settle the same rows at
	// once. Ordered by id for a deterministic lock order.
	LockPayoutsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]SupplierPayout, error)
	// Newest first: a refund goes back against the most recent money in, which
	// is the payment the customer is most likely to recognise on a statement.
	LockRefundableTopups(ctx context.Context, customerID uuid.UUID) ([]WalletTopup, error)
	LockSchedule(ctx context.Context, id uuid.UUID) (Schedule, error)
	// The row lock every balance change takes, so two movements serialise.
	LockWallet(ctx context.Context, customerID uuid.UUID) (Wallet, error)
	LookupIdempotencyKey(ctx context.Context, arg LookupIdempotencyKeyParams) (OrderIdempotency, error)
	// Marks an order paid. Filtered on pending_payment so a replayed capture
	// cannot re-run the transition, and a cancelled order cannot be resurrected.
	MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error)
	MarkOrderPaymentFailed(ctx context.Context, arg MarkOrderPaymentFailedParams) (Order, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (Outbox, error)
	MarkOutboxPublished(ctx context.Context, id uuid.UUID) (Outbox, error)
	MarkPaymentCaptured(ctx context.Context, arg MarkPaymentCapturedParams) (Payment, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error)
	// Filtered on status='pending', so a replayed mark-paid updates zero rows
	// rather than overwriting who settled it and when.
	MarkPayoutPaid(ctx context.Context, arg MarkPayoutPaidParams) (SupplierPayout, error)
	MarkWalletRefundFailed(ctx context.Context, arg MarkWalletRefundFailedParams) (WalletRefund, error)
	MarkWalletRefundIssued(ctx context.Context, arg MarkWalletRefundIssuedParams) (WalletRefund, error)
	// Closes an event: processed successfully (error NULL), or failed in a way
	// no retry can fix (error set). A closed event is never processed again.
	// Keyed by provider_event_id, which is what the handler has in hand.
	MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) (WebhookEvent, error)
	// Records a TEMPORARY failure and leaves the event open, so Razorpay's next
	// redelivery processes it again.
	MarkWebhookRetryable(ctx context.Context, arg MarkWebhookRetryableParams) (WebhookEvent, error)
	// What we earned from markup in a period: the fourth source of revenue,
	// alongside the platform fee, supplier commission and delivery margin.
	//
	// Read from what actually happened — the markup snapshotted on each line —
	// and never recomputed from today's product markup, which an admin may have
	// changed since.
	MarkupCollectedInRange(ctx context.Context, arg MarkupCollectedInRangeParams) (int64, error)
	// One order with everything an order-confirmation email needs.
	//
	// The customer's ADDRESS is not here: it lives in the profile schema, which
	// this service may not read (CLAUDE.md §3). The dispatcher fetches it over
	// HTTP from vm-profile-api.
	OrderForEmail(ctx context.Context, id uuid.UUID) (Order, error)
	// Reconciliation: what a supplier is owed on an order according to the LINE
	// ITEMS, independent of the payout row. Used by the test that proves the two
	// agree.
	PayableFromOrderItems(ctx context.Context, dollar_1 []uuid.UUID) ([]PayableFromOrderItemsRow, error)
	// ===========================================================================
	// admin: payouts — CLAUDE.md §5.3
	// ===========================================================================
	// Per-supplier settlement summary: what we owe, over how many orders, and how
	// long the oldest has been waiting.
	PayoutSummary(ctx context.Context) ([]PayoutSummaryRow, error)
	// Retention. CDC has already read these from the WAL; the table only keeps a
	// replay window.
	PruneOrderEvents(ctx context.Context, createdAt time.Time) (int64, error)
	// The dedupe guard: the unique constraint on provider_event_id means a
	// replayed delivery collides here and is never processed twice.
	// Records a delivery and claims it for processing, in one statement.
	//
	// A first delivery inserts. A redelivery of an event still open (processed_at
	// NULL: its last attempt failed for a temporary reason, or is running now)
	// counts another attempt and returns the row, so it is processed again —
	// safe, because every handler is idempotent. A redelivery of a CLOSED event
	// matches the WHERE on the conflict update, updates nothing, and returns no
	// row: pgx.ErrNoRows means "already done, answer 200".
	RecordWebhookEvent(ctx context.Context, arg RecordWebhookEventParams) (WebhookEvent, error)
	// Releases the claim so a later tick can retry.
	//
	// Sending happens AFTER the claim — an SMTP call inside the transaction would
	// hold a pooled connection open across a network round trip — so a failed send
	// must undo its claim or the day is silently lost.
	ReleaseDailyReport(ctx context.Context, reportDate time.Time) (int64, error)
	// Puts a claimed row back after a failed send.
	//
	// Claim-then-send, released on failure — the same shape as the daily report,
	// and for the same reason: an SMTP round trip inside the claiming transaction
	// would hold a pooled connection open across a network call, and a slow relay
	// would drain the pool while Postgres sat idle.
	//
	// attempts is incremented here too, so a row that keeps failing is visible
	// without joining anything.
	ReleaseOutbox(ctx context.Context, arg ReleaseOutboxParams) (int64, error)
	SetCartItemQty(ctx context.Context, arg SetCartItemQtyParams) (CartItem, error)
	SetOrderRazorpayOrderID(ctx context.Context, arg SetOrderRazorpayOrderIDParams) (Order, error)
	SetOrderSchedule(ctx context.Context, arg SetOrderScheduleParams) error
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error)
	SetScheduleStatus(ctx context.Context, arg SetScheduleStatusParams) (Schedule, error)
	// Callers hold LockWallet and write the matching ledger row in the same
	// transaction. The CHECK on balance_paise refuses an overdraft regardless.
	SetWalletBalance(ctx context.Context, arg SetWalletBalanceParams) (Wallet, error)
	SetWalletTopupRazorpayOrder(ctx context.Context, arg SetWalletTopupRazorpayOrderParams) (WalletTopup, error)
	// Filtered on 'held' so a retried settle is a no-op rather than double-counting.
	SettleReservation(ctx context.Context, arg SettleReservationParams) (StockReservation, error)
	// Sums each supplier's lines on an order, for the payout rows.
	//
	// MINUS the markup. line_total_paise is what the customer paid, which includes
	// what we added on top of the grower's price; paying that out would hand every
	// supplier our own margin. The markup is snapshotted on the line, so this
	// figure never moves when an admin reprices the product tomorrow.
	SumOrderItemsBySupplier(ctx context.Context, orderID uuid.UUID) ([]SumOrderItemsBySupplierRow, error)
	// Which pack SIZES actually sell.
	//
	// The one breakdown a grower cannot get anywhere else on the platform: they
	// choose their own units (CLAUDE.md §5.2), and nothing tells them whether the
	// 10 kg is worth listing. Instants rather than dates, matching the other
	// supplier queries this screen reuses.
	SupplierAnalyticsByPack(ctx context.Context, arg SupplierAnalyticsByPackParams) ([]SupplierAnalyticsByPackRow, error)
	// Which GRADES actually sell.
	//
	// A grower grades their produce into separate crates at separate prices
	// (CLAUDE.md §5.2) and then has to decide, next season, which grades are worth
	// picking for. Nothing else on the platform answers that: "what sold" is by
	// produce, "which packs sell" is by box size, and neither can tell an XL2 from
	// a T1.
	//
	// Grouped by PRODUCE AND grade, never by grade alone: one grower's M2
	// pomegranate and M2 tomato are different crates, and a row reading "M2" that
	// silently summed them would be worse than no row.
	//
	// Ungraded lines are excluded rather than bucketed. size_code_snapshot is NULL
	// on an ungraded listing and on any order placed before size codes existed
	// (§5.3), and an "ungraded" row would be a lump of exactly the produce this
	// breakdown has nothing to say about.
	SupplierAnalyticsBySizeCode(ctx context.Context, arg SupplierAnalyticsBySizeCodeParams) ([]SupplierAnalyticsBySizeCodeRow, error)
	// ===========================================================================
	// supplier analytics — the grower's own trend screen
	//
	// Scoped by supplier_id IN SQL, like every other supplier query: a grower must
	// never be able to read another's figures, and the WHERE clause is the
	// enforcement rather than a check the handler might forget (CLAUDE.md §7).
	//
	// Money here is the GROWER's, not the customer's: line_total minus the markup
	// that was ours. The same subtraction as SupplierSalesByProduct, so the two
	// screens cannot quote different totals for one period.
	// ===========================================================================
	// Day by day, in IST. Bounded by dates rather than instants because the
	// grouping is by calendar day, and both bounds must describe the same thing.
	SupplierAnalyticsDaily(ctx context.Context, arg SupplierAnalyticsDailyParams) ([]SupplierAnalyticsDailyRow, error)
	// The supplier's OWN lines on those orders. Filtered by supplier_id, so a
	// multi-supplier order never reveals what another grower supplied or charged.
	SupplierOrderItems(ctx context.Context, arg SupplierOrderItemsParams) ([]SupplierOrderItemsRow, error)
	// One row per order this supplier has produce in. The payout status is joined
	// so the supplier can see which orders they have already been paid for.
	SupplierOrders(ctx context.Context, arg SupplierOrdersParams) ([]SupplierOrdersRow, error)
	// The count behind the pager. Same JOIN as above so the two can never disagree
	// about which orders belong to this supplier.
	SupplierOrdersCount(ctx context.Context, arg SupplierOrdersCountParams) (int64, error)
	// What was actually sold, by produce. Snapshots, so an edited or deleted
	// product still reports correctly.
	SupplierSalesByProduct(ctx context.Context, arg SupplierSalesByProductParams) ([]SupplierSalesByProductRow, error)
	// ---------------------------------------------------------------------------
	// Supplier's own sales.
	//
	// Every query below is scoped to one supplier_id and that scope is not
	// optional (CLAUDE.md §7): a supplier must never be able to see another
	// supplier's lines, orders or amounts.
	// ---------------------------------------------------------------------------
	// Money totals come from supplier_payouts, not from order_items, deliberately:
	// payouts are exactly what the admin settlement screen pays against, so the
	// supplier's "owed" figure and the admin's "owing" figure are the same number
	// from the same row. Deriving one from items and the other from payouts is how
	// the two screens end up disagreeing at settlement time.
	// Every supplier sales query below takes the SAME optional window, as two
	// nullable timestamptz bounds: NULL and NULL mean all time.
	//
	// The bounds are instants, not dates, and the caller computes them from an IST
	// calendar day with isttime (CLAUDE.md rule 2). Doing the conversion in SQL —
	// `(placed_at AT TIME ZONE 'Asia/Kolkata')::date` — would put a second copy of
	// the timezone rule in a place no Go test covers, and would depend on the
	// database's own tzdata. The upper bound is EXCLUSIVE: it is midnight at the
	// start of the day after the range, so the last day is included whole without
	// anyone having to write 23:59:59.999.
	//
	// placed_at is the basis throughout, so the summary, the produce breakdown and
	// the order list can never describe different sets of orders.
	SupplierSalesSummary(ctx context.Context, arg SupplierSalesSummaryParams) (SupplierSalesSummaryRow, error)
	// Marks the pre-existing outbox backlog published WITHOUT sending it.
	//
	// A maintenance action, run once by hand from internal/devtools. The
	// dispatcher was added long after these rows were written, so the queue held
	// months of confirmations for orders that have already been delivered,
	// cancelled or expired. Draining it against a real relay would mail every one
	// of those customers about an order they finished with weeks ago.
	//
	// Bounded by a timestamp the caller passes, not `now()` inside the statement,
	// so a confirmation written WHILE this runs is not swallowed by it. The reason
	// is stamped on last_error rather than left blank: a row marked published that
	// nobody ever sent should say so.
	SuppressOutboxBacklog(ctx context.Context, createdAt time.Time) (int64, error)
	UpdateScheduleAddress(ctx context.Context, arg UpdateScheduleAddressParams) (Schedule, error)
	// Adding the same pack again bumps quantity rather than creating a duplicate
	// line, which is what a customer means by pressing Add twice.
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error)
}

var _ Querier = (*Queries)(nil)
